<div class="left-panel">
                    <div id="accordion">
                        <?php 
                            foreach ($this->categoryList as $key => $value) {
                        ?>
                        <a href="<?=$this->basePath()?>/application/index/product?id=<?=$value['id']?>">
                           <span><?=$value['category_name']?></span>    
                        </a>
                        
                        <div>
                            <ul class="category-sub-list list-unstyled">
                                <?php 
                                if(!empty($value['child'])){
                                    foreach ($value['child'] as $keys => $values) {
                                ?>
                                <li class="category-list_sub-item">
                                    <a href="<?=$this->basePath()?>/application/index/product?id=<?=$values['id']?>">
                                        <div class="category-item-details">
                                            <span class="name"><span><?=$values['category_name']?></span></span>
                                        </div>
                                    </a>
                                </li>
                                <?php }}?>
                                
                            </ul>
                        </div>
                        
                            <?php  }?>
                    </div>
                    <div class="col-md-12 rsidebar">
                        <div class="rsidebar-top">
                            <div class="slider-left">
                                <h4>Filter By Price</h4>            
                                <div class="row row1 scroll-pane">
                                    <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>0 - $100 </label>
                                    <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>$100 - $200 </label> 
                                    <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>$200 - $250  </label> 
                                    <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>$250 - $300 </label> 
                                    <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>$350 - $400 </label> 
                                    <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>$450 - $500  </label> 
                                    <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>More</label> 
                                </div> 
                            </div>
                            <div class="sidebar-row">
                                <h4>Dry Fruits &amp; Nuts</h4>
                                <ul class="faq">
                                    <li class="item1"><a href="#">Fruits<span class="glyphicon glyphicon-menu-down"></span></a>
                                        <ul>
                                            <li class="subitem1"><a href="#">Apple</a></li>										
                                            <li class="subitem1"><a href="#">Appricoat</a></li>										
                                            <li class="subitem1"><a href="#">Banana</a></li>										
                                            <li class="subitem1"><a href="#">Grapes</a></li>										
                                        </ul>
                                    </li>
                                    <li class="item2"><a href="#">Dry fruits<span class="glyphicon glyphicon-menu-down"></span></a>
                                        <ul>
                                            <li class="subitem1"><a href="#">Kaju</a></li>										
                                            <li class="subitem1"><a href="#">Badaam</a></li>				 										
                                            <li class="subitem1"><a href="#">Pista</a></li>										
                                            <li class="subitem1"><a href="#">Dates</a></li>										
                                        </ul>
                                    </li>
                                    <li class="item3"><a href="#">Nuts<span class="glyphicon glyphicon-menu-down"></span></a>
                                        <ul>
                                            <li class="subitem1"><a href="#">Penuts</a></li>										
                                            <li class="subitem1"><a href="#">Chilli Penuts</a></li>										
                                            <li class="subitem1"><a href="#">Salted Penuts</a></li>										
                                        </ul>
                                    </li>
                                </ul>
                                <!-- script for tabs -->
                                <script type="text/javascript">
                                    $(function () {

                                        var menu_ul = $('.faq > li > ul'),
                                                menu_a = $('.faq > li > a');

                                        menu_ul.hide();

                                        menu_a.click(function (e) {
                                            e.preventDefault();
                                            if (!$(this).hasClass('active')) {
                                                menu_a.removeClass('active');
                                                menu_ul.filter(':visible').slideUp('normal');
                                                $(this).addClass('active').next().stop(true, true).slideDown('normal');
                                            } else {
                                                $(this).removeClass('active');
                                                $(this).next().stop(true, true).slideUp('normal');
                                            }
                                        });

                                    });
                                </script>
                                <!-- script for tabs -->
                            </div>
                            <div class="sidebar-row">
                                <h4>DISCOUNTS</h4>
                                <div class="row row1 scroll-pane">
                                    <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>Upto - 10% (20)</label>
                                    <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>70% - 60% (5)</label>
                                    <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>50% - 40% (7)</label>
                                    <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>30% - 20% (2)</label>
                                    <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>10% - 5% (5)</label>
                                    <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>30% - 20% (7)</label>
                                    <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>10% - 5% (2)</label>
                                    <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>Other(50)</label>
                                </div>
                            </div> 	
                            <div class="clearfix com-marg"></div> 
                        </div>
<!--                        <div class="related-row">
                            <h4>Related Searches</h4>
                            <ul>
                                <li><a href="products.html">Yellow Moong Dal</a></li>
                                <li><a href="products.html">Rajdhani Chilka Green Moong Dal</a></li>
                                <li><a href="products.html">Organic Split Moong</a></li>
                                <li><a href="products.html">Dhuli Moong</a></li>
                                <li><a href="products.html">Economy Malka Masoor Dal</a></li>
                                <li><a href="products.html">Economy Kabuli Chana</a></li>
                            </ul>
                        </div>
                        <div class="related-row">
                            <h4>YOU MAY ALSO LIKE</h4>
                            <div class="galry-like">  
                                <a href="single.html"><img src="images/pro_367638.jpg" class="img-responsive" alt="img"></a>             
                                <h4><a href="products.html">Green Bite Dhuli Yellow Moong Dal</a></h4> 
                                <h5>GHC 100</h5>       
                            </div>
                        </div>-->
                    </div>
                </div>