
<!DOCTYPE html>

<html lang="en">  
    <body ng-controller="index" ng-cloak="true">
        <!-- header -->

        <!-- //header -->	
        <!-- banner -->
        <div class="banner">
            <div id="kb" class="carousel kb_elastic animate_text kb_wrapper" data-ride="carousel" data-interval="6000" data-pause="hover">
                <!-- Wrapper-for-Slides -->
                <div class="carousel-inner" role="listbox">
                     <?php
                        if(!empty($this->banner['data'])){
                            foreach ($this->banner['data'] as $key => $value) {
                                $imageName = $value['image_name'];
                                $path = $this->banner['imageRootPath'].'/'.$imageName;
                    ?>
                    <!--<a href="<?= !empty($value['link'])?$value['link']:'javascript:void(0)' ?>">-->
                    <div class="item <?= $key==0?'active':''?>" style="height:350px">
                        <img src="<?php echo $path; ?>" alt="" class="img-responsive"/>
                        <div class="carousel-caption kb_caption kb_caption_center">
                            <h4 data-animation="animated fadeInLeft"><?= $value['description']?></h4>
                        </div>
                    </div>
                     <!--</a>-->
                    <?php
                        }}else{
                    ?>
                    <div class="item active"> First-Slide 
                        <img src="<?php echo $this->basePath() ?>/public/images/banner1.jpg" alt="" class="img-responsive" />
                        <div class="carousel-caption kb_caption kb_caption_right">
                         </div> 
                    </div>
                        <?php }?>
                </div> 
                <!-- Left-Button -->
                <a class="left carousel-control kb_control_left" href="#kb" role="button" data-slide="prev">
                    <span class="fa fa-angle-left kb_icons" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a> 
                <!-- Right-Button -->
                <a class="right carousel-control kb_control_right" href="#kb" role="button" data-slide="next">
                    <span class="fa fa-angle-right kb_icons" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a> 
            </div>
            <script src="<?php echo $this->basePath() ?>/public/js/custom.js"></script>
        </div>
        <!-- //banner -->  
        <!---728x90---> 
        <!-- welcome -->
        <div class="welcome"> 
            <div class="container"> 
                <div class="welcome-info">
                    <div class="bs-example bs-example-tabs" role="tabpanel" data-example-id="togglable-tabs">
                        <ul id="myTab" class=" nav-tabs" role="tablist">
                            <?php
                                foreach ($this->categoryList['data'] as $key => $value) {
                            ?>
                            <li role="presentation" class="active">
                                <a href="<?=$this->basePath()?>/application/index/product?id=<?=$key?>" >
                                    <!--<i class="fa fa-laptop" aria-hidden="true"></i> -->
                                    <?php
                                        if(!empty($this->categoryList['images'][$key])){
                                            $type = $this->categoryList['images'][$key][0]['type'];
                                            $name = $this->categoryList['images'][$key][0]['image_name'];
                                            $path = $this->categoryList['imageRootPath'];
                                            $image = $path.'/'.$type.'/'.$key.'/'.$name;
                                            echo'<img src="'.$image.'" style="height: 140px;width:200px;"/>';
                                        
                                        }else{
                                            echo'<img src="'.$this->basePath().'/public/images/newimg/noimage.png" style="height: 140px;width:200px;"/>';
                                        }
                                           
                                    ?>   
                                    <h5><?=$value['category_name']?></h5>
                                </a>
                            </li>
                                <?php }?>
                        </ul>
                        <div class="clearfix"> </div>                            
                    </div>  
                </div>  	
            </div>  	
        </div>  
        <div class="container">
            <section id="demos">
                <div class="row">
                    <div style="width: 100%;">
                        <h1 class="slider-header">Most Popular
                            <a href="#" class="btn btn--link float-right weight--semibold product-slider-show-all-link push--right">View all</a></h1>
                        <div class="products products--inline">
                            <div class="owl-carousel owl-theme">
                                <div class="item">
                                    <a  href="#" class="product_wrapper">
                                        <div class="plp-product">
                                            <div  class="plp-product_offer">12% OFF</div>
                                            <div class="plp-product_offer display--none">₹ 40 Off</div>
                                            <div  class="plp-product_img "><img class="img animated fadeIn" alt="Aashirvaad Shudh Chakki Whole Wheat Atta" src="<?php echo $this->basePath() ?>/public/images/pro_333324.jpg?1475228410"></div>
                                            <div  title="Aashirvaad Shudh Chakki Whole Wheat Atta" class="plp-product_name ">
                                                <div  class="LinesEllipsis  plp-product_name--box">Aashirvaad Shudh Chakki Whole Wheat Atta
                                                </div>
                                            </div>
                                            <div title="10 kg" class="plp-product_quantity"><span>10 kg</span></div>
                                            <div  class="plp-product_price">
                                                <div  class="plp-product_price--container">
                                                    <div class="plp-product_price--old display--inline-block@mobile">₹ 330</div>
                                                    <div class="plp-product_price--new display--inline-block@mobile">₹ 290</div>
                                                </div>
                                            </div>
                                            <div class="plp-product_add-to-cart">
                                                <div class="add-to-cart">
                                                    <button data-test-id="minus-button" class="add-to-cart_dec"></button>
                                                    <button data-test-id="add-button" class="add-to-cart_add-btn display--inline-block">Add To Cart</button>
                                                    <button data-test-id="plus-button" class="add-to-cart_inc"></button>
                                                </div>
                                            </div>
                                        </div>
                                    </a>
                                </div>
                                <div class="item">
                                    <a  href="#" class="product_wrapper">
                                        <div class="plp-product">
                                            <div  class="plp-product_offer">12% OFF</div>
                                            <div class="plp-product_offer display--none">₹ 40 Off</div>
                                            <div  class="plp-product_img "><img class="img animated fadeIn" alt="Aashirvaad Shudh Chakki Whole Wheat Atta" src="<?php echo $this->basePath() ?>/public/images/pro_333324.jpg?1475228410"></div>
                                            <div  title="Aashirvaad Shudh Chakki Whole Wheat Atta" class="plp-product_name ">
                                                <div  class="LinesEllipsis  plp-product_name--box">Aashirvaad Shudh Chakki Whole Wheat Atta
                                                </div>
                                            </div>
                                            <div title="10 kg" class="plp-product_quantity"><span>10 kg</span></div>
                                            <div  class="plp-product_price">
                                                <div  class="plp-product_price--container">
                                                    <div class="plp-product_price--old display--inline-block@mobile">₹ 330</div>
                                                    <div class="plp-product_price--new display--inline-block@mobile">₹ 290</div>
                                                </div>
                                            </div>
                                            <div class="plp-product_add-to-cart">
                                                <div class="add-to-cart">
                                                    <button data-test-id="minus-button" class="add-to-cart_dec"></button>
                                                    <button data-test-id="add-button" class="add-to-cart_add-btn display--inline-block">Add To Cart</button>
                                                    <button data-test-id="plus-button" class="add-to-cart_inc"></button>
                                                </div>
                                            </div>
                                        </div>
                                    </a>
                                </div>
                                <div class="item">
                                    <a  href="#" class="product_wrapper">
                                        <div class="plp-product">
                                            <div  class="plp-product_offer">12% OFF</div>
                                            <div class="plp-product_offer display--none"><!-- react-text: 151 -->₹<!-- react-text: 152 -->40<!-- react-text: 153 --> Off</div>
                                            <div  class="plp-product_img "><img class="img animated fadeIn" alt="Aashirvaad Shudh Chakki Whole Wheat Atta" src="<?php echo $this->basePath() ?>/public/images/pro_333324.jpg?1475228410"></div>
                                            <div  title="Aashirvaad Shudh Chakki Whole Wheat Atta" class="plp-product_name ">
                                                <div  class="LinesEllipsis  plp-product_name--box"><!-- react-text: 159 -->Aashirvaad Shudh Chakki Whole Wheat Atta
                                                </div>
                                            </div>
                                            <div title="10 kg" class="plp-product_quantity"><span>10 kg</span></div>
                                            <div  class="plp-product_price">
                                                <div  class="plp-product_price--container">
                                                    <div class="plp-product_price--old display--inline-block@mobile"><!-- react-text: 166 -->₹<!-- react-text: 167 -->330</div>
                                                    <div class="plp-product_price--new display--inline-block@mobile"><!-- react-text: 169 -->₹<!-- react-text: 170 -->290</div>
                                                </div>
                                            </div>
                                            <div class="plp-product_add-to-cart">
                                                <div class="add-to-cart">
                                                    <button data-test-id="minus-button" class="add-to-cart_dec"></button>
                                                    <button data-test-id="add-button" class="add-to-cart_add-btn display--inline-block">Add To Cart</button>
                                                    <button data-test-id="plus-button" class="add-to-cart_inc"></button>
                                                </div>
                                            </div>
                                        </div>
                                    </a>
                                </div>
                                <div class="item">
                                    <a  href="#" class="product_wrapper">
                                        <div class="plp-product">
                                            <div  class="plp-product_offer">12% OFF</div>
                                            <div class="plp-product_offer display--none"><!-- react-text: 151 -->₹<!-- react-text: 152 -->40<!-- react-text: 153 --> Off</div>
                                            <div  class="plp-product_img "><img class="img animated fadeIn" alt="Aashirvaad Shudh Chakki Whole Wheat Atta" src="<?php echo $this->basePath() ?>/public/images/pro_333324.jpg?1475228410"></div>
                                            <div  title="Aashirvaad Shudh Chakki Whole Wheat Atta" class="plp-product_name ">
                                                <div  class="LinesEllipsis  plp-product_name--box"><!-- react-text: 159 -->Aashirvaad Shudh Chakki Whole Wheat Atta
                                                </div>
                                            </div>
                                            <div title="10 kg" class="plp-product_quantity"><span>10 kg</span></div>
                                            <div  class="plp-product_price">
                                                <div  class="plp-product_price--container">
                                                    <div class="plp-product_price--old display--inline-block@mobile"><!-- react-text: 166 -->₹<!-- react-text: 167 -->330</div>
                                                    <div class="plp-product_price--new display--inline-block@mobile"><!-- react-text: 169 -->₹<!-- react-text: 170 -->290</div>
                                                </div>
                                            </div>
                                            <div class="plp-product_add-to-cart">
                                                <div class="add-to-cart">
                                                    <button data-test-id="minus-button" class="add-to-cart_dec"></button>
                                                    <button data-test-id="add-button" class="add-to-cart_add-btn display--inline-block">Add To Cart</button>
                                                    <button data-test-id="plus-button" class="add-to-cart_inc"></button>
                                                </div>
                                            </div>
                                        </div>
                                    </a>
                                </div>
                                <div class="item">
                                    <a  href="#" class="product_wrapper">
                                        <div class="plp-product">
                                            <div  class="plp-product_offer">12% OFF</div>
                                            <div class="plp-product_offer display--none"><!-- react-text: 151 -->₹<!-- react-text: 152 -->40<!-- react-text: 153 --> Off</div>
                                            <div  class="plp-product_img "><img class="img animated fadeIn" alt="Aashirvaad Shudh Chakki Whole Wheat Atta" src="<?php echo $this->basePath() ?>/public/images/pro_333324.jpg?1475228410"></div>
                                            <div  title="Aashirvaad Shudh Chakki Whole Wheat Atta" class="plp-product_name ">
                                                <div  class="LinesEllipsis  plp-product_name--box"><!-- react-text: 159 -->Aashirvaad Shudh Chakki Whole Wheat Atta
                                                </div>
                                            </div>
                                            <div title="10 kg" class="plp-product_quantity"><span>10 kg</span></div>
                                            <div  class="plp-product_price">
                                                <div  class="plp-product_price--container">
                                                    <div class="plp-product_price--old display--inline-block@mobile"><!-- react-text: 166 -->₹<!-- react-text: 167 -->330</div>
                                                    <div class="plp-product_price--new display--inline-block@mobile"><!-- react-text: 169 -->₹<!-- react-text: 170 -->290</div>
                                                </div>
                                            </div>
                                            <div class="plp-product_add-to-cart">
                                                <div class="add-to-cart">
                                                    <button data-test-id="minus-button" class="add-to-cart_dec"></button>
                                                    <button data-test-id="add-button" class="add-to-cart_add-btn display--inline-block">Add To Cart</button>
                                                    <button data-test-id="plus-button" class="add-to-cart_inc"></button>
                                                </div>
                                            </div>
                                        </div>
                                    </a>
                                </div>
                                <div class="item">
                                    <a  href="#" class="product_wrapper">
                                        <div class="plp-product">
                                            <div  class="plp-product_offer">12% OFF</div>
                                            <div class="plp-product_offer display--none"><!-- react-text: 151 -->₹<!-- react-text: 152 -->40<!-- react-text: 153 --> Off</div>
                                            <div  class="plp-product_img "><img class="img animated fadeIn" alt="Aashirvaad Shudh Chakki Whole Wheat Atta" src="<?php echo $this->basePath() ?>/public/images/pro_333324.jpg?1475228410"></div>
                                            <div  title="Aashirvaad Shudh Chakki Whole Wheat Atta" class="plp-product_name ">
                                                <div  class="LinesEllipsis  plp-product_name--box"><!-- react-text: 159 -->Aashirvaad Shudh Chakki Whole Wheat Atta
                                                </div>
                                            </div>
                                            <div title="10 kg" class="plp-product_quantity"><span>10 kg</span></div>
                                            <div  class="plp-product_price">
                                                <div  class="plp-product_price--container">
                                                    <div class="plp-product_price--old display--inline-block@mobile"><!-- react-text: 166 -->₹<!-- react-text: 167 -->330</div>
                                                    <div class="plp-product_price--new display--inline-block@mobile"><!-- react-text: 169 -->₹<!-- react-text: 170 -->290</div>
                                                </div>
                                            </div>
                                            <div class="plp-product_add-to-cart">
                                                <div class="add-to-cart">
                                                    <button data-test-id="minus-button" class="add-to-cart_dec"></button>
                                                    <button data-test-id="add-button" class="add-to-cart_add-btn display--inline-block">Add To Cart</button>
                                                    <button data-test-id="plus-button" class="add-to-cart_inc"></button>
                                                </div>
                                            </div>
                                        </div>
                                    </a>
                                </div>
                                <div class="item">
                                    <a  href="#" class="product_wrapper">
                                        <div class="plp-product">
                                            <div  class="plp-product_offer">12% OFF</div>
                                            <div class="plp-product_offer display--none"><!-- react-text: 151 -->₹<!-- react-text: 152 -->40<!-- react-text: 153 --> Off</div>
                                            <div  class="plp-product_img "><img class="img animated fadeIn" alt="Aashirvaad Shudh Chakki Whole Wheat Atta" src="<?php echo $this->basePath() ?>/public/images/pro_333324.jpg?1475228410"></div>
                                            <div  title="Aashirvaad Shudh Chakki Whole Wheat Atta" class="plp-product_name ">
                                                <div  class="LinesEllipsis  plp-product_name--box"><!-- react-text: 159 -->Aashirvaad Shudh Chakki Whole Wheat Atta
                                                </div>
                                            </div>
                                            <div title="10 kg" class="plp-product_quantity"><span>10 kg</span></div>
                                            <div  class="plp-product_price">
                                                <div  class="plp-product_price--container">
                                                    <div class="plp-product_price--old display--inline-block@mobile"><!-- react-text: 166 -->₹<!-- react-text: 167 -->330</div>
                                                    <div class="plp-product_price--new display--inline-block@mobile"><!-- react-text: 169 -->₹<!-- react-text: 170 -->290</div>
                                                </div>
                                            </div>
                                            <div class="plp-product_add-to-cart">
                                                <div class="add-to-cart">
                                                    <button data-test-id="minus-button" class="add-to-cart_dec"></button>
                                                    <button data-test-id="add-button" class="add-to-cart_add-btn display--inline-block">Add To Cart</button>
                                                    <button data-test-id="plus-button" class="add-to-cart_inc"></button>
                                                </div>
                                            </div>
                                        </div>
                                    </a>
                                </div>
                                <div class="item">
                                    <a  href="#" class="product_wrapper">
                                        <div class="plp-product">
                                            <div  class="plp-product_offer">12% OFF</div>
                                            <div class="plp-product_offer display--none"><!-- react-text: 151 -->₹<!-- react-text: 152 -->40<!-- react-text: 153 --> Off</div>
                                            <div  class="plp-product_img "><img class="img animated fadeIn" alt="Aashirvaad Shudh Chakki Whole Wheat Atta" src="<?php echo $this->basePath() ?>/public/images/pro_333324.jpg?1475228410"></div>
                                            <div  title="Aashirvaad Shudh Chakki Whole Wheat Atta" class="plp-product_name ">
                                                <div  class="LinesEllipsis  plp-product_name--box"><!-- react-text: 159 -->Aashirvaad Shudh Chakki Whole Wheat Atta
                                                </div>
                                            </div>
                                            <div title="10 kg" class="plp-product_quantity"><span>10 kg</span></div>
                                            <div  class="plp-product_price">
                                                <div  class="plp-product_price--container">
                                                    <div class="plp-product_price--old display--inline-block@mobile"><!-- react-text: 166 -->₹<!-- react-text: 167 -->330</div>
                                                    <div class="plp-product_price--new display--inline-block@mobile"><!-- react-text: 169 -->₹<!-- react-text: 170 -->290</div>
                                                </div>
                                            </div>
                                            <div class="plp-product_add-to-cart">
                                                <div class="add-to-cart">
                                                    <button data-test-id="minus-button" class="add-to-cart_dec"></button>
                                                    <button data-test-id="add-button" class="add-to-cart_add-btn display--inline-block">Add To Cart</button>
                                                    <button data-test-id="plus-button" class="add-to-cart_inc"></button>
                                                </div>
                                            </div>
                                        </div>
                                    </a>
                                </div>
                                <div class="item">
                                    <a  href="#" class="product_wrapper">
                                        <div class="plp-product">
                                            <div  class="plp-product_offer">12% OFF</div>
                                            <div class="plp-product_offer display--none"><!-- react-text: 151 -->₹<!-- react-text: 152 -->40<!-- react-text: 153 --> Off</div>
                                            <div  class="plp-product_img "><img class="img animated fadeIn" alt="Aashirvaad Shudh Chakki Whole Wheat Atta" src="<?php echo $this->basePath() ?>/public/images/pro_333324.jpg?1475228410"></div>
                                            <div  title="Aashirvaad Shudh Chakki Whole Wheat Atta" class="plp-product_name ">
                                                <div  class="LinesEllipsis  plp-product_name--box"><!-- react-text: 159 -->Aashirvaad Shudh Chakki Whole Wheat Atta
                                                </div>
                                            </div>
                                            <div title="10 kg" class="plp-product_quantity"><span>10 kg</span></div>
                                            <div  class="plp-product_price">
                                                <div  class="plp-product_price--container">
                                                    <div class="plp-product_price--old display--inline-block@mobile"><!-- react-text: 166 -->₹<!-- react-text: 167 -->330</div>
                                                    <div class="plp-product_price--new display--inline-block@mobile"><!-- react-text: 169 -->₹<!-- react-text: 170 -->290</div>
                                                </div>
                                            </div>
                                            <div class="plp-product_add-to-cart">
                                                <div class="add-to-cart">
                                                    <button data-test-id="minus-button" class="add-to-cart_dec"></button>
                                                    <button data-test-id="add-button" class="add-to-cart_add-btn display--inline-block">Add To Cart</button>
                                                    <button data-test-id="plus-button" class="add-to-cart_inc"></button>
                                                </div>
                                            </div>
                                        </div>
                                    </a>
                                </div>
                                <div class="item">
                                    <a  href="#" class="product_wrapper">
                                        <div class="plp-product">
                                            <div  class="plp-product_offer">12% OFF</div>
                                            <div class="plp-product_offer display--none"><!-- react-text: 151 -->₹<!-- react-text: 152 -->40<!-- react-text: 153 --> Off</div>
                                            <div  class="plp-product_img "><img class="img animated fadeIn" alt="Aashirvaad Shudh Chakki Whole Wheat Atta" src="<?php echo $this->basePath() ?>/public/images/pro_333324.jpg?1475228410"></div>
                                            <div  title="Aashirvaad Shudh Chakki Whole Wheat Atta" class="plp-product_name ">
                                                <div  class="LinesEllipsis  plp-product_name--box"><!-- react-text: 159 -->Aashirvaad Shudh Chakki Whole Wheat Atta
                                                </div>
                                            </div>
                                            <div title="10 kg" class="plp-product_quantity"><span>10 kg</span></div>
                                            <div  class="plp-product_price">
                                                <div  class="plp-product_price--container">
                                                    <div class="plp-product_price--old display--inline-block@mobile"><!-- react-text: 166 -->₹<!-- react-text: 167 -->330</div>
                                                    <div class="plp-product_price--new display--inline-block@mobile"><!-- react-text: 169 -->₹<!-- react-text: 170 -->290</div>
                                                </div>
                                            </div>
                                            <div class="plp-product_add-to-cart">
                                                <div class="add-to-cart">
                                                    <button data-test-id="minus-button" class="add-to-cart_dec"></button>
                                                    <button data-test-id="add-button" class="add-to-cart_add-btn display--inline-block">Add To Cart</button>
                                                    <button data-test-id="plus-button" class="add-to-cart_inc"></button>
                                                </div>
                                            </div>
                                        </div>
                                    </a>
                                </div>
                                <div class="item">
                                    <a  href="#" class="product_wrapper">
                                        <div class="plp-product">
                                            <div  class="plp-product_offer">12% OFF</div>
                                            <div class="plp-product_offer display--none"><!-- react-text: 151 -->₹<!-- react-text: 152 -->40<!-- react-text: 153 --> Off</div>
                                            <div  class="plp-product_img "><img class="img animated fadeIn" alt="Aashirvaad Shudh Chakki Whole Wheat Atta" src="<?php echo $this->basePath() ?>/public/images/pro_333324.jpg?1475228410"></div>
                                            <div  title="Aashirvaad Shudh Chakki Whole Wheat Atta" class="plp-product_name ">
                                                <div  class="LinesEllipsis  plp-product_name--box"><!-- react-text: 159 -->Aashirvaad Shudh Chakki Whole Wheat Atta
                                                </div>
                                            </div>
                                            <div title="10 kg" class="plp-product_quantity"><span>10 kg</span></div>
                                            <div  class="plp-product_price">
                                                <div  class="plp-product_price--container">
                                                    <div class="plp-product_price--old display--inline-block@mobile"><!-- react-text: 166 -->₹<!-- react-text: 167 -->330</div>
                                                    <div class="plp-product_price--new display--inline-block@mobile"><!-- react-text: 169 -->₹<!-- react-text: 170 -->290</div>
                                                </div>
                                            </div>
                                            <div class="plp-product_add-to-cart">
                                                <div class="add-to-cart">
                                                    <button data-test-id="minus-button" class="add-to-cart_dec"></button>
                                                    <button data-test-id="add-button" class="add-to-cart_add-btn display--inline-block">Add To Cart</button>
                                                    <button data-test-id="plus-button" class="add-to-cart_inc"></button>
                                                </div>
                                            </div>
                                        </div>
                                    </a>
                                </div>
                                <div class="item">
                                    <a  href="#" class="product_wrapper">
                                        <div class="plp-product">
                                            <div  class="plp-product_offer">12% OFF</div>
                                            <div class="plp-product_offer display--none">₹ 40 Off</div>
                                            <div  class="plp-product_img "><img class="img animated fadeIn" alt="Aashirvaad Shudh Chakki Whole Wheat Atta" src="<?php echo $this->basePath() ?>/public/images/pro_333324.jpg?1475228410"></div>
                                            <div  title="Aashirvaad Shudh Chakki Whole Wheat Atta" class="plp-product_name ">
                                                <div  class="LinesEllipsis  plp-product_name--box">Aashirvaad Shudh Chakki Whole Wheat Atta
                                                </div>
                                            </div>
                                            <div title="10 kg" class="plp-product_quantity"><span>10 kg</span></div>
                                            <div  class="plp-product_price">
                                                <div  class="plp-product_price--container">
                                                    <div class="plp-product_price--old display--inline-block@mobile">₹ 330</div>
                                                    <div class="plp-product_price--new display--inline-block@mobile">₹ 290</div>
                                                </div>
                                            </div>
                                            <div class="plp-product_add-to-cart">
                                                <div class="add-to-cart">
                                                    <button data-test-id="minus-button" class="add-to-cart_dec"></button>
                                                    <button data-test-id="add-button" class="add-to-cart_add-btn display--inline-block">Add To Cart</button>
                                                    <button data-test-id="plus-button" class="add-to-cart_inc"></button>
                                                </div>
                                            </div>
                                        </div>
                                    </a>
                                </div>
                            </div>  

                        </div>
                    </div>


                    <div style="width: 100%;">

                        <h1 class="slider-header">DEALS OF THE DAY 
                            <a href="#" class="btn btn--link float-right weight--semibold product-slider-show-all-link push--right">View all</a></h1>
                        <div class="products products--inline">
                            <div class="owl-carousel owl-theme">
                                <div class="item">
                                    <a  href="#" class="product_wrapper">
                                        <div class="plp-product">
                                            <div  class="plp-product_offer">12% OFF</div>
                                            <div class="plp-product_offer display--none">₹ 40 Off</div>
                                            <div  class="plp-product_img "><img class="img animated fadeIn" alt="Aashirvaad Shudh Chakki Whole Wheat Atta" <?php echo $this->basePath() ?>/public/images/pro_333324.jpg?1475228410"></div>
                                            <div  title="Aashirvaad Shudh Chakki Whole Wheat Atta" class="plp-product_name ">
                                                <div  class="LinesEllipsis  plp-product_name--box">Aashirvaad Shudh Chakki Whole Wheat Atta
                                                </div>
                                            </div>
                                            <div title="10 kg" class="plp-product_quantity"><span>10 kg</span></div>
                                            <div  class="plp-product_price">
                                                <div  class="plp-product_price--container">
                                                    <div class="plp-product_price--old display--inline-block@mobile">₹ 330</div>
                                                    <div class="plp-product_price--new display--inline-block@mobile">₹ 290</div>
                                                </div>
                                            </div>
                                            <div class="plp-product_add-to-cart">
                                                <div class="add-to-cart">
                                                    <button data-test-id="minus-button" class="add-to-cart_dec"></button>
                                                    <button data-test-id="add-button" class="add-to-cart_add-btn display--inline-block">Add To Cart</button>
                                                    <button data-test-id="plus-button" class="add-to-cart_inc"></button>
                                                </div>
                                            </div>
                                        </div>
                                    </a>
                                </div>
                                <div class="item">
                                    <a  href="#" class="product_wrapper">
                                        <div class="plp-product">
                                            <div  class="plp-product_offer">12% OFF</div>
                                            <div class="plp-product_offer display--none">₹ 40 Off</div>
                                            <div  class="plp-product_img "><img class="img animated fadeIn" alt="Aashirvaad Shudh Chakki Whole Wheat Atta" src="<?php echo $this->basePath() ?>/public/images/pro_333324.jpg?1475228410"></div>
                                            <div  title="Aashirvaad Shudh Chakki Whole Wheat Atta" class="plp-product_name ">
                                                <div  class="LinesEllipsis  plp-product_name--box">Aashirvaad Shudh Chakki Whole Wheat Atta
                                                </div>
                                            </div>
                                            <div title="10 kg" class="plp-product_quantity"><span>10 kg</span></div>
                                            <div  class="plp-product_price">
                                                <div  class="plp-product_price--container">
                                                    <div class="plp-product_price--old display--inline-block@mobile">₹ 330</div>
                                                    <div class="plp-product_price--new display--inline-block@mobile">₹ 290</div>
                                                </div>
                                            </div>
                                            <div class="plp-product_add-to-cart">
                                                <div class="add-to-cart">
                                                    <button data-test-id="minus-button" class="add-to-cart_dec"></button>
                                                    <button data-test-id="add-button" class="add-to-cart_add-btn display--inline-block">Add To Cart</button>
                                                    <button data-test-id="plus-button" class="add-to-cart_inc"></button>
                                                </div>
                                            </div>
                                        </div>
                                    </a>
                                </div>
                                <div class="item">
                                    <a  href="#" class="product_wrapper">
                                        <div class="plp-product">
                                            <div  class="plp-product_offer">12% OFF</div>
                                            <div class="plp-product_offer display--none"><!-- react-text: 151 -->₹<!-- react-text: 152 -->40<!-- react-text: 153 --> Off</div>
                                            <div  class="plp-product_img "><img class="img animated fadeIn" alt="Aashirvaad Shudh Chakki Whole Wheat Atta" src="<?php echo $this->basePath() ?>/public/images/pro_333324.jpg?1475228410"></div>
                                            <div  title="Aashirvaad Shudh Chakki Whole Wheat Atta" class="plp-product_name ">
                                                <div  class="LinesEllipsis  plp-product_name--box"><!-- react-text: 159 -->Aashirvaad Shudh Chakki Whole Wheat Atta
                                                </div>
                                            </div>
                                            <div title="10 kg" class="plp-product_quantity"><span>10 kg</span></div>
                                            <div  class="plp-product_price">
                                                <div  class="plp-product_price--container">
                                                    <div class="plp-product_price--old display--inline-block@mobile"><!-- react-text: 166 -->₹<!-- react-text: 167 -->330</div>
                                                    <div class="plp-product_price--new display--inline-block@mobile"><!-- react-text: 169 -->₹<!-- react-text: 170 -->290</div>
                                                </div>
                                            </div>
                                            <div class="plp-product_add-to-cart">
                                                <div class="add-to-cart">
                                                    <button data-test-id="minus-button" class="add-to-cart_dec"></button>
                                                    <button data-test-id="add-button" class="add-to-cart_add-btn display--inline-block">Add To Cart</button>
                                                    <button data-test-id="plus-button" class="add-to-cart_inc"></button>
                                                </div>
                                            </div>
                                        </div>
                                    </a>
                                </div>
                                <div class="item">
                                    <a  href="#" class="product_wrapper">
                                        <div class="plp-product">
                                            <div  class="plp-product_offer">12% OFF</div>
                                            <div class="plp-product_offer display--none"><!-- react-text: 151 -->₹<!-- react-text: 152 -->40<!-- react-text: 153 --> Off</div>
                                            <div  class="plp-product_img "><img class="img animated fadeIn" alt="Aashirvaad Shudh Chakki Whole Wheat Atta" src="<?php echo $this->basePath() ?>/public/images/pro_333324.jpg?1475228410"></div>
                                            <div  title="Aashirvaad Shudh Chakki Whole Wheat Atta" class="plp-product_name ">
                                                <div  class="LinesEllipsis  plp-product_name--box"><!-- react-text: 159 -->Aashirvaad Shudh Chakki Whole Wheat Atta
                                                </div>
                                            </div>
                                            <div title="10 kg" class="plp-product_quantity"><span>10 kg</span></div>
                                            <div  class="plp-product_price">
                                                <div  class="plp-product_price--container">
                                                    <div class="plp-product_price--old display--inline-block@mobile"><!-- react-text: 166 -->₹<!-- react-text: 167 -->330</div>
                                                    <div class="plp-product_price--new display--inline-block@mobile"><!-- react-text: 169 -->₹<!-- react-text: 170 -->290</div>
                                                </div>
                                            </div>
                                            <div class="plp-product_add-to-cart">
                                                <div class="add-to-cart">
                                                    <button data-test-id="minus-button" class="add-to-cart_dec"></button>
                                                    <button data-test-id="add-button" class="add-to-cart_add-btn display--inline-block">Add To Cart</button>
                                                    <button data-test-id="plus-button" class="add-to-cart_inc"></button>
                                                </div>
                                            </div>
                                        </div>
                                    </a>
                                </div>
                                <div class="item">
                                    <a  href="#" class="product_wrapper">
                                        <div class="plp-product">
                                            <div  class="plp-product_offer">12% OFF</div>
                                            <div class="plp-product_offer display--none"><!-- react-text: 151 -->₹<!-- react-text: 152 -->40<!-- react-text: 153 --> Off</div>
                                            <div  class="plp-product_img "><img class="img animated fadeIn" alt="Aashirvaad Shudh Chakki Whole Wheat Atta" src="<?php echo $this->basePath() ?>/public/images/pro_333324.jpg?1475228410"></div>
                                            <div  title="Aashirvaad Shudh Chakki Whole Wheat Atta" class="plp-product_name ">
                                                <div  class="LinesEllipsis  plp-product_name--box"><!-- react-text: 159 -->Aashirvaad Shudh Chakki Whole Wheat Atta
                                                </div>
                                            </div>
                                            <div title="10 kg" class="plp-product_quantity"><span>10 kg</span></div>
                                            <div  class="plp-product_price">
                                                <div  class="plp-product_price--container">
                                                    <div class="plp-product_price--old display--inline-block@mobile"><!-- react-text: 166 -->₹<!-- react-text: 167 -->330</div>
                                                    <div class="plp-product_price--new display--inline-block@mobile"><!-- react-text: 169 -->₹<!-- react-text: 170 -->290</div>
                                                </div>
                                            </div>
                                            <div class="plp-product_add-to-cart">
                                                <div class="add-to-cart">
                                                    <button data-test-id="minus-button" class="add-to-cart_dec"></button>
                                                    <button data-test-id="add-button" class="add-to-cart_add-btn display--inline-block">Add To Cart</button>
                                                    <button data-test-id="plus-button" class="add-to-cart_inc"></button>
                                                </div>
                                            </div>
                                        </div>
                                    </a>
                                </div>
                                <div class="item">
                                    <a  href="#" class="product_wrapper">
                                        <div class="plp-product">
                                            <div  class="plp-product_offer">12% OFF</div>
                                            <div class="plp-product_offer display--none"><!-- react-text: 151 -->₹<!-- react-text: 152 -->40<!-- react-text: 153 --> Off</div>
                                            <div  class="plp-product_img "><img class="img animated fadeIn" alt="Aashirvaad Shudh Chakki Whole Wheat Atta" src="<?php echo $this->basePath() ?>/public/images/pro_333324.jpg?1475228410"></div>
                                            <div  title="Aashirvaad Shudh Chakki Whole Wheat Atta" class="plp-product_name ">
                                                <div  class="LinesEllipsis  plp-product_name--box"><!-- react-text: 159 -->Aashirvaad Shudh Chakki Whole Wheat Atta
                                                </div>
                                            </div>
                                            <div title="10 kg" class="plp-product_quantity"><span>10 kg</span></div>
                                            <div  class="plp-product_price">
                                                <div  class="plp-product_price--container">
                                                    <div class="plp-product_price--old display--inline-block@mobile"><!-- react-text: 166 -->₹<!-- react-text: 167 -->330</div>
                                                    <div class="plp-product_price--new display--inline-block@mobile"><!-- react-text: 169 -->₹<!-- react-text: 170 -->290</div>
                                                </div>
                                            </div>
                                            <div class="plp-product_add-to-cart">
                                                <div class="add-to-cart">
                                                    <button data-test-id="minus-button" class="add-to-cart_dec"></button>
                                                    <button data-test-id="add-button" class="add-to-cart_add-btn display--inline-block">Add To Cart</button>
                                                    <button data-test-id="plus-button" class="add-to-cart_inc"></button>
                                                </div>
                                            </div>
                                        </div>
                                    </a>
                                </div>
                                <div class="item">
                                    <a  href="#" class="product_wrapper">
                                        <div class="plp-product">
                                            <div  class="plp-product_offer">12% OFF</div>
                                            <div class="plp-product_offer display--none"><!-- react-text: 151 -->₹<!-- react-text: 152 -->40<!-- react-text: 153 --> Off</div>
                                            <div  class="plp-product_img "><img class="img animated fadeIn" alt="Aashirvaad Shudh Chakki Whole Wheat Atta" src="<?php echo $this->basePath() ?>/public/images/pro_333324.jpg?1475228410"></div>
                                            <div  title="Aashirvaad Shudh Chakki Whole Wheat Atta" class="plp-product_name ">
                                                <div  class="LinesEllipsis  plp-product_name--box"><!-- react-text: 159 -->Aashirvaad Shudh Chakki Whole Wheat Atta
                                                </div>
                                            </div>
                                            <div title="10 kg" class="plp-product_quantity"><span>10 kg</span></div>
                                            <div  class="plp-product_price">
                                                <div  class="plp-product_price--container">
                                                    <div class="plp-product_price--old display--inline-block@mobile"><!-- react-text: 166 -->₹<!-- react-text: 167 -->330</div>
                                                    <div class="plp-product_price--new display--inline-block@mobile"><!-- react-text: 169 -->₹<!-- react-text: 170 -->290</div>
                                                </div>
                                            </div>
                                            <div class="plp-product_add-to-cart">
                                                <div class="add-to-cart">
                                                    <button data-test-id="minus-button" class="add-to-cart_dec"></button>
                                                    <button data-test-id="add-button" class="add-to-cart_add-btn display--inline-block">Add To Cart</button>
                                                    <button data-test-id="plus-button" class="add-to-cart_inc"></button>
                                                </div>
                                            </div>
                                        </div>
                                    </a>
                                </div>
                                <div class="item">
                                    <a  href="#" class="product_wrapper">
                                        <div class="plp-product">
                                            <div  class="plp-product_offer">12% OFF</div>
                                            <div class="plp-product_offer display--none"><!-- react-text: 151 -->₹<!-- react-text: 152 -->40<!-- react-text: 153 --> Off</div>
                                            <div  class="plp-product_img "><img class="img animated fadeIn" alt="Aashirvaad Shudh Chakki Whole Wheat Atta" src="<?php echo $this->basePath() ?>/public/images/pro_333324.jpg?1475228410"></div>
                                            <div  title="Aashirvaad Shudh Chakki Whole Wheat Atta" class="plp-product_name ">
                                                <div  class="LinesEllipsis  plp-product_name--box"><!-- react-text: 159 -->Aashirvaad Shudh Chakki Whole Wheat Atta
                                                </div>
                                            </div>
                                            <div title="10 kg" class="plp-product_quantity"><span>10 kg</span></div>
                                            <div  class="plp-product_price">
                                                <div  class="plp-product_price--container">
                                                    <div class="plp-product_price--old display--inline-block@mobile"><!-- react-text: 166 -->₹<!-- react-text: 167 -->330</div>
                                                    <div class="plp-product_price--new display--inline-block@mobile"><!-- react-text: 169 -->₹<!-- react-text: 170 -->290</div>
                                                </div>
                                            </div>
                                            <div class="plp-product_add-to-cart">
                                                <div class="add-to-cart">
                                                    <button data-test-id="minus-button" class="add-to-cart_dec"></button>
                                                    <button data-test-id="add-button" class="add-to-cart_add-btn display--inline-block">Add To Cart</button>
                                                    <button data-test-id="plus-button" class="add-to-cart_inc"></button>
                                                </div>
                                            </div>
                                        </div>
                                    </a>
                                </div>
                                <div class="item">
                                    <a  href="#" class="product_wrapper">
                                        <div class="plp-product">
                                            <div  class="plp-product_offer">12% OFF</div>
                                            <div class="plp-product_offer display--none"><!-- react-text: 151 -->₹<!-- react-text: 152 -->40<!-- react-text: 153 --> Off</div>
                                            <div  class="plp-product_img "><img class="img animated fadeIn" alt="Aashirvaad Shudh Chakki Whole Wheat Atta" src="<?php echo $this->basePath() ?>/public/images/pro_333324.jpg?1475228410"></div>
                                            <div  title="Aashirvaad Shudh Chakki Whole Wheat Atta" class="plp-product_name ">
                                                <div  class="LinesEllipsis  plp-product_name--box"><!-- react-text: 159 -->Aashirvaad Shudh Chakki Whole Wheat Atta
                                                </div>
                                            </div>
                                            <div title="10 kg" class="plp-product_quantity"><span>10 kg</span></div>
                                            <div  class="plp-product_price">
                                                <div  class="plp-product_price--container">
                                                    <div class="plp-product_price--old display--inline-block@mobile"><!-- react-text: 166 -->₹<!-- react-text: 167 -->330</div>
                                                    <div class="plp-product_price--new display--inline-block@mobile"><!-- react-text: 169 -->₹<!-- react-text: 170 -->290</div>
                                                </div>
                                            </div>
                                            <div class="plp-product_add-to-cart">
                                                <div class="add-to-cart">
                                                    <button data-test-id="minus-button" class="add-to-cart_dec"></button>
                                                    <button data-test-id="add-button" class="add-to-cart_add-btn display--inline-block">Add To Cart</button>
                                                    <button data-test-id="plus-button" class="add-to-cart_inc"></button>
                                                </div>
                                            </div>
                                        </div>
                                    </a>
                                </div>
                                <div class="item">
                                    <a  href="#" class="product_wrapper">
                                        <div class="plp-product">
                                            <div  class="plp-product_offer">12% OFF</div>
                                            <div class="plp-product_offer display--none"><!-- react-text: 151 -->₹<!-- react-text: 152 -->40<!-- react-text: 153 --> Off</div>
                                            <div  class="plp-product_img "><img class="img animated fadeIn" alt="Aashirvaad Shudh Chakki Whole Wheat Atta" src="<?php echo $this->basePath() ?>/public/images/pro_333324.jpg?1475228410"></div>
                                            <div  title="Aashirvaad Shudh Chakki Whole Wheat Atta" class="plp-product_name ">
                                                <div  class="LinesEllipsis  plp-product_name--box"><!-- react-text: 159 -->Aashirvaad Shudh Chakki Whole Wheat Atta
                                                </div>
                                            </div>
                                            <div title="10 kg" class="plp-product_quantity"><span>10 kg</span></div>
                                            <div  class="plp-product_price">
                                                <div  class="plp-product_price--container">
                                                    <div class="plp-product_price--old display--inline-block@mobile"><!-- react-text: 166 -->₹<!-- react-text: 167 -->330</div>
                                                    <div class="plp-product_price--new display--inline-block@mobile"><!-- react-text: 169 -->₹<!-- react-text: 170 -->290</div>
                                                </div>
                                            </div>
                                            <div class="plp-product_add-to-cart">
                                                <div class="add-to-cart">
                                                    <button data-test-id="minus-button" class="add-to-cart_dec"></button>
                                                    <button data-test-id="add-button" class="add-to-cart_add-btn display--inline-block">Add To Cart</button>
                                                    <button data-test-id="plus-button" class="add-to-cart_inc"></button>
                                                </div>
                                            </div>
                                        </div>
                                    </a>
                                </div>
                                <div class="item">
                                    <a  href="#" class="product_wrapper">
                                        <div class="plp-product">
                                            <div  class="plp-product_offer">12% OFF</div>
                                            <div class="plp-product_offer display--none"><!-- react-text: 151 -->₹<!-- react-text: 152 -->40<!-- react-text: 153 --> Off</div>
                                            <div  class="plp-product_img "><img class="img animated fadeIn" alt="Aashirvaad Shudh Chakki Whole Wheat Atta" src="<?php echo $this->basePath() ?>/public/images/pro_333324.jpg?1475228410"></div>
                                            <div  title="Aashirvaad Shudh Chakki Whole Wheat Atta" class="plp-product_name ">
                                                <div  class="LinesEllipsis  plp-product_name--box"><!-- react-text: 159 -->Aashirvaad Shudh Chakki Whole Wheat Atta
                                                </div>
                                            </div>
                                            <div title="10 kg" class="plp-product_quantity"><span>10 kg</span></div>
                                            <div  class="plp-product_price">
                                                <div  class="plp-product_price--container">
                                                    <div class="plp-product_price--old display--inline-block@mobile"><!-- react-text: 166 -->₹<!-- react-text: 167 -->330</div>
                                                    <div class="plp-product_price--new display--inline-block@mobile"><!-- react-text: 169 -->₹<!-- react-text: 170 -->290</div>
                                                </div>
                                            </div>
                                            <div class="plp-product_add-to-cart">
                                                <div class="add-to-cart">
                                                    <button data-test-id="minus-button" class="add-to-cart_dec"></button>
                                                    <button data-test-id="add-button" class="add-to-cart_add-btn display--inline-block">Add To Cart</button>
                                                    <button data-test-id="plus-button" class="add-to-cart_inc"></button>
                                                </div>
                                            </div>
                                        </div>
                                    </a>
                                </div>
                                <div class="item">
                                    <a  href="#" class="product_wrapper">
                                        <div class="plp-product">
                                            <div  class="plp-product_offer">12% OFF</div>
                                            <div class="plp-product_offer display--none">₹ 40 Off</div>
                                            <div  class="plp-product_img "><img class="img animated fadeIn" alt="Aashirvaad Shudh Chakki Whole Wheat Atta" src="<?php echo $this->basePath() ?>/public/images/pro_333324.jpg?1475228410"></div>
                                            <div  title="Aashirvaad Shudh Chakki Whole Wheat Atta" class="plp-product_name ">
                                                <div  class="LinesEllipsis  plp-product_name--box">Aashirvaad Shudh Chakki Whole Wheat Atta
                                                </div>
                                            </div>
                                            <div title="10 kg" class="plp-product_quantity"><span>10 kg</span></div>
                                            <div  class="plp-product_price">
                                                <div  class="plp-product_price--container">
                                                    <div class="plp-product_price--old display--inline-block@mobile">₹ 330</div>
                                                    <div class="plp-product_price--new display--inline-block@mobile">₹ 290</div>
                                                </div>
                                            </div>
                                            <div class="plp-product_add-to-cart">
                                                <div class="add-to-cart">
                                                    <button data-test-id="minus-button" class="add-to-cart_dec"></button>
                                                    <button data-test-id="add-button" class="add-to-cart_add-btn display--inline-block">Add To Cart</button>
                                                    <button data-test-id="plus-button" class="add-to-cart_inc"></button>
                                                </div>
                                            </div>
                                        </div>
                                    </a>
                                </div>
                            </div>  

                        </div>
                    </div>

                    <div style="width: 100%;">

                        <h1 class="slider-header">Merchant
                            <a href="#" class="btn btn--link float-right weight--semibold product-slider-show-all-link push--right">View all</a></h1>
                        <div class="products products--inline">
                            <div class="owl-carousel owl-theme">
                                <?php 
                                    foreach ($this->marchantList as $key => $value) {
                                ?>
                                <div class="item">
                                    <a  href="<?=$this->basePath()?>/application/index/product?merchant=<?=$value['id']?>" class="product_wrapper">
                                        <div class="plp-product">
                                            <div  class="plp-product_img merchant">
                                                <img class="img animated fadeIn" alt="" src="<?php echo $this->basePath() ?>/public/images/newimg/noimagemerchant.jpeg"></div>
                                            <div  title="<?= $value['first_name']?>" class="plp-product_name ">
                                                <div  class="merchant_name"><?= $value['first_name']?> </div>
                                            </div>
                                            <div class="plp-product_add-to-cart">
                                                <div class="add-to-cart">
                                                   <button data-test-id="add-button" class="add-to-cart_add-btn display--inline-block">Shop Now</button>
                                                </div>
                                            </div>
                                        </div>
                                    </a>
                                </div>
                                <?php
                                }
                                ?>
                            </div>  

                        </div>
                    </div>
                </div>
            </section>

            <div class="w3agile-ftr-top"><img src="<?php echo $this->basePath() ?>/public/images/shop1.jpg" class="img-responsive"/></div>
            <div class="w3agile-ftr-top subscribe-right"><img src="<?php echo $this->basePath() ?>/public/images/shop.jpg" class="img-responsive"/> 
            </div>
        </div>
        <!-- //footer-top --> 
        <!-- subscribe -->
        <div class="subscribe"> 
            <div class="container">
                <div class="col-md-6 social-icons w3-agile-icons">
                    <h4>Keep in touch</h4>  
                    <ul>
                        <li><a href="#" class="fa fa-facebook icon facebook"> </a></li>
                        <li><a href="#" class="fa fa-twitter icon twitter"> </a></li>
                        <li><a href="#" class="fa fa-google-plus icon googleplus"> </a></li>
                        <li><a href="#" class="fa fa-dribbble icon dribbble"> </a></li>
                        <li><a href="#" class="fa fa-rss icon rss"> </a></li> 
                    </ul> 
                    <ul class="apps"> 
                        <li><h4>Download Our app : </h4> </li>
                        <li><a href="#" class="fa fa-apple"></a></li>
                        <li><a href="#" class="fa fa-windows"></a></li>
                        <li><a href="#" class="fa fa-android"></a></li>
                    </ul> 
                </div> 
                <div class="col-md-6 subscribe-right no-rpad no-lpad">
                    <h4>Sign up for email and get 25%off!</h4>  
                    <form action="#" method="post"> 
                        <input type="text" name="email" placeholder="Enter your Email..." required="">
                        <input type="submit" value="Subscribe">
                    </form>
                    <div class="clearfix"> </div> 
                </div>
                <div class="clearfix"> </div>
            </div>
        </div>
        <!-- //subscribe --> 
        <!-- footer -->

        <!-- //footer -->		
        <div class="copy-right"> 
            <div class="container">
                <p>© 2017 Afro Basket . All rights reserved | Design by <a href="#"> Designer Rakesh.</a></p>
            </div>
        </div> 


        <div class="" id="city-box" style="display: none;"> 
            <div class="location__shake-container animated">
                
<!--                <div class="location">
                    <div>
                        <div class="location-body">
                            <div class="location-body__top-container">
                                <div class="location-helper weight--semibold text-center">Where do you want the delivery?</div>
                                <div class="location__selected"><img class="img animated fadeIn location-body__selected-image" alt="Gurugram / Faridabad" src="<?php echo $this->basePath() ?>/public/images/gurugram-ff049a38d323a7bf38f44435af2e61ed.png">
                                    <div class="location-body__selected-body">
                                        <div class="location-body__selected-title"> react-text: 1114 Deliver in  /react-text <span class="weight--semibold">Gurugram / Faridabad</span></div>
                                        <span class="location-body__right-arrow" data-test-id="location-right-arrow"></span></div>
                                </div>
                            </div>
                            <div class="location-body__bottom-container">
                                <div class="location-body__bottom-wrapper">
                                    <div class="location__separator"><span class="separator-text">Or Select your city</span></div>
                                    <div class="cities-container">
                                        <div class="cities-container__title">Top Searched Cities</div>
                                        <div class="cities-container-list">
                                            <div class="cities-container-list__item">
                                                <select class="form-control select2" style="width: 100%;">
                                                <?php
                                                    foreach ($this->cityList as $key => $value) {
//                                                        echo'<div class="cities-container-list__item-name">'.$value['city_name'].'</div>';
                                                        echo'<option >'.$value['city_name'].'</option>';
                                                    }
                                                ?>
                                                </select>
                                            </div>
                                            
                                        </div>
                                    </div>
                                    <div class="location-autosuggest">
                                        <div class="location-autosuggest__select-container" data-test-id="location-input-box">
                                            <div class="relative"><span class="location-autosuggest__select-icon"></span>
                                                <div class="Select location-autosuggest__select Select--single is-searchable">
                                                    <div class="Select-control"><span class="Select-multi-value-wrapper" id="react-select-2--value">
                                                            <div class="Select-placeholder">Type your city (e.g Chennai, Pune)</div>
                                                            <div class="Select-input" style="display: inline-block;">
                                                                <input role="combobox" aria-expanded="false" aria-owns="" aria-haspopup="false" aria-activedescendant="react-select-2--value" value="" style="width: 17px; box-sizing: content-box;">
                                                                <div style="position: absolute; top: 0px; left: 0px; visibility: hidden; height: 0px; overflow: scroll; white-space: pre;"></div>
                                                            </div>
                                                        </span><span class="Select-arrow-zone"><span class="Select-arrow"></span></span></div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="location-autosuggest__button-container"><a class="location-autosuggest__button"><span class="location-autosuggest__button-icon"></span><span class="display--inline-block weight--normal">Detect</span></a></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>-->
            </div>
        </div>

    </body>
</html>
<script src="<?php echo $this->basePath() . '/public/js/frontend/index.js' ?>">
</script>