<!DOCTYPE html>
<html lang="en">
    <body ng-controller="login">
        <div class="login-page">
            <div class="container"> 
                <h3 class="w3ls-title w3ls-title1 subscribe-right">  Login to your account</h3> 
                <h4 class="danger" style="color:red" ng-show="errorShow">{{errorMsg}}</h4>
                <h4 class="danger" style="color:green" ng-show="successShow">{{successMsg}}</h4>
                <div class="login-body">
                    <form  method="post">
                        <input type="text" class="user" name="email" ng-model="loginData.email" placeholder="Enter your email" required="">
                        <input type="password" name="password" ng-model="loginData.password" class="lock" placeholder="Password" required="">
                        <input type="submit" value="Login" ng-click="login(loginData)">
                        <div class="forgot-grid">
                            <!--<label class="checkbox"><input type="checkbox" name="checkbox"><i></i>Remember me</label>-->
                            <div class="forgot">
                                <a href="<?=$this->basePath()?>/application/index/forgetpassword">Forgot Password?</a>
                            </div>
                            <div class="clearfix"> </div>
                        </div>
                    </form>
                </div>  
                <h6> Not a Member? <a  href="<?=$this->basePath()?>/application/index/signup">Sign Up Now »</a> </h6> 
                <div class="login-page-bottom social-icons">
                    <h5>Recover your social account</h5>
                    <ul>
                        <li><a href="#" class="fa fa-facebook icon facebook"> </a></li>
                        <li><a href="#" class="fa fa-twitter icon twitter"> </a></li>
                        <li><a href="#" class="fa fa-google-plus icon googleplus"> </a></li>
                        <li><a href="#" class="fa fa-dribbble icon dribbble"> </a></li>
                        <li><a href="#" class="fa fa-rss icon rss"> </a></li> 
                    </ul> 
                </div>
            </div>
        </div>
        <div style="position: fixed; top: 0; left: 0; background: rgba(0,0,0,0.3); z-index: 99999999; width: 100%; height: 100%;"  ng-show="ajaxLoadingData">
            <img style="position: absolute; top: 40%; left: 45%; width: 250px; " alt="loader" src="<?=$this->basePath()?>/public/images/loading_cart.gif">
        </div>
        <!-- //login-page --> 


    </body>
</html>
<script src="<?php echo $this->basePath() . '/public/js/frontend/login.js' ?>">
</script>