<!DOCTYPE html>
<html lang="en">
    <body ng-app="app" ng-controller="login">
        <div class="login-page">
            <div class="container"> 
                <h3 class="w3ls-title w3ls-title1 subscribe-right">  Login to your account</h3> 
                <h4 class="danger" style="color:red" ng-show="errorShow">{{errorMsg}}</h4>
                <h4 class="danger" style="color:green" ng-show="successShow">{{successMsg}}</h4>
                <div class="login-body">
                    <form  method="post">
                        <input type="text" class="user" name="email" ng-model="loginData.email" placeholder="Enter your email" required="">
                        <input type="password" name="password" ng-model="loginData.password" class="lock" placeholder="Password" required="">
                        <input type="submit" value="Login" ng-click="login(loginData)">
                        <div class="forgot-grid">
                            <!--<label class="checkbox"><input type="checkbox" name="checkbox"><i></i>Remember me</label>-->
                            <div class="forgot">
                                <a href="#">Forgot Password?</a>
                            </div>
                            <div class="clearfix"> </div>
                        </div>
                    </form>
                </div>  
                <h6> Not a Member? <a  href="<?=$this->basePath()?>/application/index/signup">Sign Up Now »</a> </h6> 
                <div class="login-page-bottom social-icons">
                    <h5>Recover your social account</h5>
                    <ul>
                        <li><a href="#" class="fa fa-facebook icon facebook"> </a></li>
                        <li><a href="#" class="fa fa-twitter icon twitter"> </a></li>
                        <li><a href="#" class="fa fa-google-plus icon googleplus"> </a></li>
                        <li><a href="#" class="fa fa-dribbble icon dribbble"> </a></li>
                        <li><a href="#" class="fa fa-rss icon rss"> </a></li> 
                    </ul> 
                </div>
            </div>
        </div>
        <!-- //login-page --> 

        <div class="copy-right"> 
            <div class="container">
                <p>© 2017 Afro Basket . All rights reserved | Design by <a href="#"> Designer Rakesh.</a></p>
            </div>
        </div> 

    </body>
</html>
<script src="<?php echo $this->basePath() . '/public/js/frontend/login.js' ?>">
</script>