
<div class="right-panel"  ng-app="app" ng-cloak="true" ng-controller="product">
    <div class="full-width"> 
        <ol class="breadcrumb breadcrumb1 relative pdp_top-container" >
            <li><a href="#">Home</a></li>
            <li class="active"><?= $this->categoryName ?></li>	
            <div class="pull-right">
                <div class="plp-sort-dd">                  
                    <label class="dropdown_title-label" for="dd-title-label">Sort by</label>
                    <select>
                        <option>Relevance</option>
                        <option>Low to High</option>
                        <option>High to Low</option>
                        <option>Name (A To Z)</option>
                    </select>
                </div>
            </div>		
        </ol>

        <div class="clearfix"> </div>
    </div>

    <div class="category-navs">
        <div class="clearfix com-marg"> </div>
        <p class="danger" style="color:red" ng-show="errorShow">{{errorMsg}}</p>
        <p class="danger" style="color:green" ng-show="successShow">{{successMsg}}</p>
    </div>
    <div class="products products--grid">   
        <div ng-show="no_record != ''"> 
            <h4 style="color:red;"> {{no_record}}</h4>
        </div>
        <a class="product_wrapper" href="javascript:void(0)">
            <div class="plp-product">
                <!--<div class="plp-product_offer">19% OFF</div>-->
                <div class="plp-product_offer display--none"><!-- react-text: 3259 -->GHC<!-- /react-text --><!-- react-text: 3260 -->30<!-- /react-text --><!-- react-text: 3261 --> Off<!-- /react-text --></div>
                <div class="plp-product_img ">
                    <img class="img animated fadeIn"  src="images" style="width:200px">
                </div>
                <div class="plp-product_name " title="product_name">
                    <div class="LinesEllipsis  plp-product_name--box">{{product_name}}<wbr></wbr>
                    </div>
                </div>
                <div class="plp-product_quantity" title="">
                    <span>
                        {{attribute_name}}
                    </span>
                </div>
                <select class="form-control " style="width: 100%;">
                    <option value="attribute"> 1kg</option>
                    <option value="attribute"> 1kg</option>
                </select>
                <!--div class="plp-product_price">
                    <div class="plp-product_price--container">
                        <input type="hidden" id="att_<?= $key ?>">
                        <div class="plp-product_price--new display--inline-block@mobile" id="<?= $key ?>"></div>
                    </div>
                </div-->
                <div class="plp-product_add-to-cart">
                    <div class="add-to-cart">
                        <button class="add-to-cart_dec" data-test-id="minus-button"></button>
                        <button class="add-to-cart_add-btn display--inline-block" data-test-id="add-button" ng-click="addtocart()">Add To Cart</button>
                        <button class="add-to-cart_inc" data-test-id="plus-button"></button>
                    </div>
                </div>
            </div>
        </a>
    </div> 
</div>
</div>
</div>

<!-- //subscribe --> 
<!-- footer -->
<!-- //footer -->		
<div class="copy-right"> 
    <div class="container">
        <p>© 2017 Afro Basket . All rights reserved | Design by <a href="#"> Designer Rakesh.</a></p>
    </div>
</div>   
</html>
<script src="<?php echo $this->basePath() . '/public/js/frontend/product.js' ?>">
</script>
<script>
    app.value('productData', <?php echo $this->categoryId;?>);
</script>