<div class="col-main col-sm-9 col-sm-push-3 product-grid" ng-cloak="true" ng-controller="product">
    <div class="pro-coloumn">
        <article class="col-main">
            <div class="toolbar">
                <div class="sorter">
                    
                </div>
                <div id="sort-by">
                    <label class="left">Sort By: </label>
                    <ul>
                        <li><a href="#">Position<span class="right-arrow"></span></a>
                            <ul>
                                <li><a href="#">Name</a></li>
                                <li><a href="#">Price</a></li>
                                <li><a href="#">Position</a></li>
                            </ul>
                        </li>
                    </ul>
                    <a class="button-asc left" href="#" title="Set Descending Direction"><span class="top_arrow"></span></a> </div>
                <div class="pager">                    
                    <div class="pages">
                        <label>Page:</label>
                            <pagination  class="pagination pull-right mt0" ng-model="currentPage" total-items="numberOfRecord" max-size="3" boundary-links="true" ng-click="selectPage(currentPage)"></pagination>
                                           
                    </div>
                </div>
            </div>
            <div class="category-products">
                <ul class="products-grid">
                    <li class="item col-lg-4 col-md-3 col-sm-4 col-xs-6" ng-repeat="product in productDataList track by $index">
                        <div class="item-inner">
                            <div class="item-img">
                                <div class="item-img-info"><a href="<?=$this->basePath()?>/index.php/application/index/productdetails?id={{product.product_id}}-{{quantity[product.product_id]}}" title="{{product.product_name}}" class="product-image"><img src="{{allProductListResponse.imageRootPath}}/{{allProductListResponse.productImageData[product.product_id][0].type}}/{{product.product_id}}/{{allProductListResponse.productImageData[product.product_id][0].image_name}}" alt="Retis lapen casen"></a>

                                    <div class="item-box-hover">
                                    </div>
                                </div>
                            </div>
                            <div class="item-info">
                                <div class="info-inner">
                                    <div class="item-title">
                                        <a href="<?=$this->basePath()?>/index.php/application/index/productdetails?id={{product.product_id}}-{{quantity[product.product_id]}}" title="{{product.product_name}}">
                                            {{product.product_name}}
                                            <none ng-if="product.brand_name">({{product.brand_name}})</none>
                                        </a> 
                                    </div>
                                    <div class="item-content">
                                   
                                        <div>                    
                                            <select id="selectBox_{{$index}}" ng-mouseover="delete($index)" style="border:1px solid #FF3300; border-radius:4px; padding:4px; width:120px;" ng-model="quantity[product.product_id]">
                                                <option ng-repeat="attributeDetails in product.attribute track by $index" ng-value="attributeDetails.attribute_id" ng-selected="1">
                                                    {{setAttribute(attributeDetails, $index)}}
                                                    {{attributeDetails.quantity}} {{attributeDetails.unit}}
                                                </option>
                                            </select>  
                                        </div>                                        
                                        <div class="add_cart">                                            
                                            <div class="price-box">
                                                <span ng-if="product.attribute[quantity[product.product_id]].discount_value && product.attribute[quantity[product.product_id]].discount_value!='0'">(
                                                    <span ng-if="product.attribute[quantity[product.product_id]].discount_type!='percent'">GHC </span>
                                                        {{product.attribute[quantity[product.product_id]].discount_value}}
                                                    <span ng-if="product.attribute[quantity[product.product_id]].discount_type=='percent'">%</span> OFF
                                                    )
                                                </span>  
                                                <span ng-if="product.discount_value && product.attribute[quantity[product.product_id]].discount_value=='0' && product.discount_value!='0'">
                                                    (
                                                    <span ng-if="product.discount_type=='flat'">GHC </span>{{product.discount_value}} 
                                                    <span ng-if="product.discount_type=='percent'">%</span> OFF
                                                    )
                                                </span>                                                
                                                <span class="regular-price" id="product-price-1"><span class="price">GHC {{product.attribute[quantity[product.product_id]].actual_price}}</span> </span> 
                                            </div>
                                        </div>
                                        <div class="add_cart add-to-cart">
                                            <button ng-if="!cartResponse.data[product.attribute[quantity[product.product_id]].id].number_of_item" class="button btn-cart" type="button" ng-click="addToCart(product.attribute[quantity[product.product_id]].id, product.product_name, 'add', 1)"><span>Add to Cart</span></button>
                                            
                                            <span ng-if="cartResponse.data[product.attribute[quantity[product.product_id]].id].number_of_item">
                                            <i class="fa fa-plus green-text" ng-click="addToCart(product.attribute[quantity[product.product_id]].id, product.product_name, 'add', 1)"></i> 
                                            <b>&nbsp;{{cartResponse.data[product.attribute[quantity[product.product_id]].id].number_of_item}}&nbsp;</b>
                                            <i class="fa fa-minus red-text" ng-click="addToCart(product.attribute[quantity[product.product_id]].id, product.product_name, 'delete', 1)"></i>                       
                                            </span>     
                                            
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </li>
                </ul>
            </div>
        </article>
    </div>
    <!--	///*///======    End article  ========= //*/// --> 
</div>
<div style="position: fixed; top: 0; left: 0; background: rgba(0,0,0,0.3); z-index: 99999999; width: 100%; height: 100%;"  ng-show="ajaxLoadingData">
    <img style="position: absolute; top: 40%; left: 45%; width: 250px; " alt="loader" src="<?= $this->basePath() ?>/public/images/loading_cart.gif">
</div>
<script type="text/javascript" src="<?= $this->basePath() ?>/public/js/frontend/product.js"></script>
<script>
    var PAGE_COUNT = 5;
    var PAGING_GAP = 3;    
    app.value('searchBy', <?php echo json_encode($this->searchBy); ?>);
    app.value('page', 'product');
   
</script>