    <style>
            .products--grid .product_wrapper{width:100%;}
            .com-marg{margin-bottom:2.4em;}
        </style>
    <div ng-controller="productdetails">
        <div class="container subscribe-right"> 
            <ol class="breadcrumb breadcrumb1">
                <li>Home</li>
                <li class="active">Product</li>
            </ol> 
            <div class="clearfix"> </div>
        </div>
        <!-- //breadcrumbs -->
        <!-- products -->
        <div class="products">	 
            <div class="container">
                <div class="single-page">
                    <div class="single-page-row" id="detail-21">
                        <div class="col-md-6 single-top-left">
                            <p class="danger" style="color:red" ng-show="errorShow">{{errorMsg}}</p>
                             <p class="danger" style="color:green" ng-show="successShow">{{successMsg}}</p>
                            <div class="flexslider">
                                <ul class="slides">
                                    <li data-thumb="images/si-1.jpg">
                                        <div class="thumb-image detail_images"> <img src="images/si-1.jpg" data-imagezoom="true" class="img-responsive" alt=""> </div>
                                    </li>
                                    <li data-thumb="images/si.jpg">
                                        <div class="thumb-image"> <img src="<?=$this->productImage?>" data-imagezoom="true" class="img-responsive" alt=""> </div>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-md-6 single-top-right">
                            <h3 class="item_name"><?= !empty($this->productDetails['product_name'])?$this->productDetails['product_name']:''?></h3>
                            <!--<p>Processing Time: Item will be shipped out within 1 working days. </p>-->
                            <div class="single-rating">
                                <ul>
                                    <li><i class="fa fa-star-o" aria-hidden="true"></i></li>
                                    <li><i class="fa fa-star-o" aria-hidden="true"></i></li>
                                    <li><i class="fa fa-star-o" aria-hidden="true"></i></li>
                                    <li><i class="fa fa-star-o" aria-hidden="true"></i></li>
                                    <li><i class="fa fa-star-o" aria-hidden="true"></i></li>
                                    <li class="rating">20 reviews</li>
                                    <li><a href="#">Add your review</a></li>
                                </ul> 
                            </div>
                            <div class="single-price">
                                <?php 
                                    if(!empty($this->productDetails['attribute'])){
                                        foreach ($this->productDetails['attribute'] as $key => $value) {
                                            $price = $value['price'];
                                            $id = $value['id'];
                                        }
                                    }
                                ?>
                                <ul>
                                    <li>GHC <?= $price?></li> 
                                    <!--<li><span class="w3off">10% OFF</span></li>--> 
                                    <!--<li>Ends on: Dec,5th</li>-->
                                    <li><a href="#"><i class="fa fa-gift" aria-hidden="true"></i> Coupon</a></li>
                                </ul>	
                            </div> 
                            <p class="single-price-text"><?= !empty($this->productDetails['product_desc'])?$this->productDetails['product_desc']:''?> </p>
                            <form >
                                <input type="hidden" name="number_of_item" value="1" />
                                <input type="hidden" name="action" value="add" /> 
                                <input type="hidden" name="item_name" value="<?=$this->productDetails['product_name']?>" /> 
                                <input type="hidden" name="merchant_inventry_id" value="<?=$id?>" /> 
                                <input type="hidden" name="gotoproductpage" value="<?=$this->productDetails['category_id']?>" /> 
                                <button type="button" class="w3ls-cart" ng-click="addtocart('<?=$this->productDetails['product_id']?>','<?=$this->productDetails['product_name']?>','<?=$id?>')" ><i class="fa fa-cart-plus" aria-hidden="true"></i> Add to cart</button>
                            </form>
                            <button class="w3ls-cart " ng-click="proceedtocheckout()"><i class="fa fa-heart-o" aria-hidden="true"></i> Proceed To Checkout</button>
                        </div>
                        <div class="clearfix"> </div>  
                    </div>
                </div> 
                <!-- collapse-tabs -->
                <div class="collpse tabs">
                    <h3 class="w3ls-title">About this item</h3> 
                    <div class="panel-group collpse" id="accordion" role="tablist" aria-multiselectable="true">
                        <div class="panel panel-default">
                            <div class="panel-heading" role="tab" id="headingOne">
                                <h4 class="panel-title">
                                    <a class="pa_italic" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                        <i class="fa fa-file-text-o fa-icon" aria-hidden="true"></i> Description <span class="fa fa-angle-down fa-arrow" aria-hidden="true"></span> <i class="fa fa-angle-up fa-arrow" aria-hidden="true"></i>
                                    </a>
                                </h4>
                            </div>
                            <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
                                <div class="panel-body">
                                    <?= !empty($this->productDetails['product_desc'])?$this->productDetails['product_desc']:''?>
                                    <?php
                                    if(!empty($this->productDetails['bullet_desc'])) {
                                        echo "<ul style='margin-left:15px;'>";
                                        foreach($this->productDetails['bullet_desc'] as $bullets) {
                                            echo "<li> $bullets</li>";
                                        }
                                        echo "</ul>";
                                    }
                                    ?>
                                </div>
                            </div>
                        </div>
                        <div class="panel panel-default">
                            <div class="panel-heading" role="tab" id="headingTwo">
                                <h4 class="panel-title">
                                    <a class="collapsed pa_italic" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                                        <i class="fa fa-info-circle fa-icon" aria-hidden="true"></i> additional information <span class="fa fa-angle-down fa-arrow" aria-hidden="true"></span> <i class="fa fa-angle-up fa-arrow" aria-hidden="true"></i>
                                    </a> 
                                </h4>
                            </div>
                            <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
                                <div class="panel-body">
                                    <?php
                                    if(!empty($this->productDetails['custom_info'])){
                                        foreach ($this->productDetails['custom_info'] as $key => $value) {
                                            echo $key .' : ' .$value.'<br>';
                                        }
                                    }
                                    ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                
            </div>
        </div>
        <div style="position: fixed; top: 0; left: 0; background: rgba(0,0,0,0.3); z-index: 99999999; width: 100%; height: 100%;"  ng-show="ajaxLoadingData">
            <img style="position: absolute; top: 40%; left: 45%; width: 250px; " alt="loader" src="<?=$this->basePath()?>/public/images/loading_cart.gif">
        </div>
    </div>
    <script src="<?php echo $this->basePath() . '/public/js/frontend/productdetails.js' ?>">
</script>
