<!DOCTYPE html>
<html lang="en">
<body>
<!-- header -->
<!-- //header -->
<!-- breadcrumbs -->
<div class="container subscribe-right">
  <ol class="breadcrumb breadcrumb1">
    <li><a href="<?=$this->basePath()?>/">Home</a></li>
    <li class="active">Terms and Conditions</li>
  </ol>
  <div class="clearfix"> </div>
</div>
<STYLE TYPE="text/css">
	<!--
		@page { margin: 1in }
		.pagehtml P { margin-bottom: 0.08in; direction: ltr; widows: 2; orphans: 2; font-size:13px;color:#000;}
		.pagehtml a:link { color: #689f39; so-language: zxx }
		p.headingpage {
    font-size: 17px;
}
	-->
	</STYLE>
<div class="pagehtml container">
  <p class="MsoNormal" style="margin-top:6.4pt;margin-right:0in;margin-bottom:6.4pt;
margin-left:0in;line-height:normal;mso-outline-level:4;background:white"><u><span lang="EN-IN" style="font-size:11.5pt;font-family:&quot;Arial&quot;,sans-serif;mso-fareast-font-family:
&quot;Times New Roman&quot;;color:#555555;mso-fareast-language:EN-IN">INTRODUCTION</span></u><span lang="EN-IN" style="font-size:11.5pt;font-family:&quot;Arial&quot;,sans-serif;mso-fareast-font-family:
&quot;Times New Roman&quot;;color:#555555;mso-fareast-language:EN-IN"><o:p></o:p></span></p>

<p class="MsoNormal" style="margin-bottom:0in;margin-bottom:.0001pt;line-height:
normal"><span lang="EN-IN" style="font-size:9.0pt;font-family:&quot;Arial&quot;,sans-serif;
mso-fareast-font-family:&quot;Times New Roman&quot;;color:#555555;mso-fareast-language:
EN-IN"><br>
<span style="background:white">Welcome to CRTUP.IN ("Website", "we", "our", or "us"). These Terms & Conditions govern your access to and use of www.crtup.in, including all services, products, features, and content available through the Website.

By accessing or using this Website, you acknowledge that you have read, understood, and agree to be bound by these Terms & Conditions. If you do not agree with any part of these Terms, please do not use our Website.

We reserve the right to modify, update, or replace these Terms & Conditions at any time without prior notice. Any changes will become effective immediately upon posting on the Website. Your continued use of the Website after such changes constitutes your acceptance of the revised Terms..</span><br>
<br>
<br style="mso-special-character:line-break">
<!--[if !supportLineBreakNewLine]--><br style="mso-special-character:line-break">
<!--[endif]--></span><span lang="EN-IN" style="font-size:12.0pt;font-family:&quot;Times New Roman&quot;,serif;
mso-fareast-font-family:&quot;Times New Roman&quot;;mso-fareast-language:EN-IN"><o:p></o:p></span></p>

<p class="MsoNormal" style="margin-top:6.4pt;margin-right:0in;margin-bottom:6.4pt;
margin-left:0in;line-height:normal;mso-outline-level:4;background:white"><u><span lang="EN-IN" style="font-size:11.5pt;font-family:&quot;Arial&quot;,sans-serif;mso-fareast-font-family:
&quot;Times New Roman&quot;;color:#555555;mso-fareast-language:EN-IN">USE OF THE SITE</span></u><span lang="EN-IN" style="font-size:11.5pt;font-family:&quot;Arial&quot;,sans-serif;mso-fareast-font-family:
&quot;Times New Roman&quot;;color:#555555;mso-fareast-language:EN-IN"><o:p></o:p></span></p>

<p class="MsoNormal" style="margin-bottom:6.4pt;line-height:normal;background:
white"><span lang="EN-IN" style="font-size:9.0pt;font-family:&quot;Arial&quot;,sans-serif;
mso-fareast-font-family:&quot;Times New Roman&quot;;color:#555555;mso-fareast-language:
EN-IN">By using this Website, you confirm that you are at least 18 years of age or are accessing the Website under the supervision of a parent or legal guardian.</br>

CRTUP.IN grants you a limited, non-exclusive, non-transferable, and revocable license to access and use this Website solely for personal shopping purposes. Commercial use, resale, or use on behalf of another person or organization without our prior written permission is strictly prohibited.</br></br>

You agree not to:</br></br>

Use the Website for any unlawful purpose.</br>
Attempt to gain unauthorized access to our systems.</br>
Interfere with the operation or security of the Website.</br>
Upload or transmit malicious software or harmful content.</br>

Any violation of these Terms may result in immediate suspension or termination of your access to the Website.</span></p>

<p class="MsoNormal" style="margin-bottom:6.4pt;line-height:normal;background:
white"><span lang="EN-IN" style="font-size:12.0pt;font-family:&quot;Times New Roman&quot;,serif;
mso-fareast-font-family:&quot;Times New Roman&quot;;mso-fareast-language:EN-IN"><o:p>&nbsp;</o:p></span></p>

<p class="MsoNormal" style="margin-top:6.4pt;margin-right:0in;margin-bottom:6.4pt;
margin-left:0in;line-height:normal;mso-outline-level:4;background:white"><u><span lang="EN-IN" style="font-size:11.5pt;font-family:&quot;Arial&quot;,sans-serif;mso-fareast-font-family:
&quot;Times New Roman&quot;;color:#555555;mso-fareast-language:EN-IN">USER SUBMISSIONS</span></u><span lang="EN-IN" style="font-size:11.5pt;font-family:&quot;Arial&quot;,sans-serif;mso-fareast-font-family:
&quot;Times New Roman&quot;;color:#555555;mso-fareast-language:EN-IN"><o:p></o:p></span></p>

<p class="MsoNormal" style="margin-bottom:6.4pt;line-height:normal;background:
white"><span lang="EN-IN" style="font-size:9.0pt;font-family:&quot;Arial&quot;,sans-serif;
mso-fareast-font-family:&quot;Times New Roman&quot;;color:#555555;mso-fareast-language:
EN-IN">Any questions, suggestions, reviews, comments, feedback, or other materials submitted by you through the Website ("Submissions") may be used by CRTUP.IN for improving our services, marketing, or other lawful business purposes.

By submitting content, you grant CRTUP.IN a non-exclusive, royalty-free, worldwide license to use, reproduce, publish, display, and distribute such content.

You agree not to submit false, misleading, defamatory, offensive, unlawful, or infringing content. We reserve the right to remove or edit any user submissions without prior notice if they violate these Terms or applicable laws.<br style="mso-special-character:line-break">
<!--[if !supportLineBreakNewLine]--><br style="mso-special-character:line-break">
<!--[endif]--></span><span lang="EN-IN" style="font-size:12.0pt;font-family:&quot;Times New Roman&quot;,serif;
mso-fareast-font-family:&quot;Times New Roman&quot;;mso-fareast-language:EN-IN"><o:p></o:p></span></p>

<p class="MsoNormal" style="margin-top:6.4pt;margin-right:0in;margin-bottom:6.4pt;
margin-left:0in;line-height:normal;mso-outline-level:4;background:white"><u><span lang="EN-IN" style="font-size:11.5pt;font-family:&quot;Arial&quot;,sans-serif;mso-fareast-font-family:
&quot;Times New Roman&quot;;color:#555555;mso-fareast-language:EN-IN">ORDER ACCEPTANCE
AND PRICING</span></u><span lang="EN-IN" style="font-size:11.5pt;font-family:
&quot;Arial&quot;,sans-serif;mso-fareast-font-family:&quot;Times New Roman&quot;;color:#555555;
mso-fareast-language:EN-IN"><o:p></o:p></span></p>

<p class="MsoNormal" style="margin-bottom:6.4pt;line-height:normal;background:
white"><span lang="EN-IN" style="font-size:9.0pt;font-family:&quot;Arial&quot;,sans-serif;
mso-fareast-font-family:&quot;Times New Roman&quot;;color:#555555;mso-fareast-language:
EN-IN">All orders placed through CRTUP.IN are subject to acceptance and product availability.</br>

We reserve the right to refuse, cancel, or limit any order for reasons including but not limited to product unavailability, pricing errors, suspected fraudulent activity, incorrect customer information, or violations of these Terms.</br>

Additional verification of your identity, contact details, or payment information may be requested before processing an order.</br>

Although we make every effort to ensure accurate pricing, occasional errors may occur. If a product is listed at an incorrect price due to technical or human error, we reserve the right to cancel the order and notify you accordingly. If payment has already been made, the amount will be refunded using the original payment method.</br>

All prices displayed on CRTUP.IN are in Indian Rupees (INR) unless otherwise stated and are subject to change without prior notice.<br style="mso-special-character:line-break">
<!--[if !supportLineBreakNewLine]--><br style="mso-special-character:line-break">
<!--[endif]--></span><span lang="EN-IN" style="font-size:12.0pt;font-family:&quot;Times New Roman&quot;,serif;
mso-fareast-font-family:&quot;Times New Roman&quot;;mso-fareast-language:EN-IN"><o:p></o:p></span></p>

<p class="MsoNormal" style="margin-top:6.4pt;margin-right:0in;margin-bottom:6.4pt;
margin-left:0in;line-height:normal;mso-outline-level:4;background:white"><u><span lang="EN-IN" style="font-size:11.5pt;font-family:&quot;Arial&quot;,sans-serif;mso-fareast-font-family:
&quot;Times New Roman&quot;;color:#555555;mso-fareast-language:EN-IN">TRADEMARKS AND
COPYRIGHTS</span></u><span lang="EN-IN" style="font-size:11.5pt;font-family:&quot;Arial&quot;,sans-serif;
mso-fareast-font-family:&quot;Times New Roman&quot;;color:#555555;mso-fareast-language:
EN-IN"><o:p></o:p></span></p>

<p class="MsoNormal" style="margin-bottom:6.4pt;line-height:normal;background:
white"><span lang="EN-IN" style="font-size:9.0pt;font-family:&quot;Arial&quot;,sans-serif;
mso-fareast-font-family:&quot;Times New Roman&quot;;color:#555555;mso-fareast-language:
EN-IN">All content available on CRTUP.IN, including but not limited to text, graphics, logos, icons, images, videos, software, website design, product descriptions, and source code, is the intellectual property of CRTUP.IN or its licensors and is protected under applicable copyright, trademark, and intellectual property laws of India.</br>

No content from this Website may be copied, reproduced, modified, distributed, transmitted, displayed, or otherwise used without prior written permission from CRTUP.IN.<br style="mso-special-character:line-break">
<!--[if !supportLineBreakNewLine]--><br style="mso-special-character:line-break">
<!--[endif]--></span><span lang="EN-IN" style="font-size:12.0pt;font-family:&quot;Times New Roman&quot;,serif;
mso-fareast-font-family:&quot;Times New Roman&quot;;mso-fareast-language:EN-IN"><o:p></o:p></span></p>

<p class="MsoNormal" style="margin-top:6.4pt;margin-right:0in;margin-bottom:6.4pt;
margin-left:0in;line-height:normal;mso-outline-level:4;background:white"><u><span lang="EN-IN" style="font-size:11.5pt;font-family:&quot;Arial&quot;,sans-serif;mso-fareast-font-family:
&quot;Times New Roman&quot;;color:#555555;mso-fareast-language:EN-IN">ARBITRATIONS</span></u><span lang="EN-IN" style="font-size:11.5pt;font-family:&quot;Arial&quot;,sans-serif;mso-fareast-font-family:
&quot;Times New Roman&quot;;color:#555555;mso-fareast-language:EN-IN"><o:p></o:p></span></p>

<p class="MsoNormal" style="margin-bottom:6.4pt;line-height:normal;background:
white"><span lang="EN-IN" style="font-size:9.0pt;font-family:&quot;Arial&quot;,sans-serif;
mso-fareast-font-family:&quot;Times New Roman&quot;;color:#555555;mso-fareast-language:
EN-IN">Any dispute, controversy, or claim arising out of or relating to these Terms and Conditions or the use of the Website shall first be attempted to be resolved amicably through mutual discussion.</br>

If the dispute cannot be resolved, it shall be referred to arbitration in accordance with the provisions of the Arbitration and Conciliation Act, 1996 of India. The arbitration shall be conducted by a sole arbitrator appointed in accordance with applicable law. The arbitration proceedings shall be conducted in English, and the decision of the arbitrator shall be final and binding on both parties.</br>

Nothing contained herein shall prevent CRTUP.IN from seeking interim or injunctive relief before a court of competent jurisdiction to protect its intellectual property rights or confidential information..</span><span lang="EN-IN" style="font-size:12.0pt;font-family:&quot;Times New Roman&quot;,serif;mso-fareast-font-family:
&quot;Times New Roman&quot;;mso-fareast-language:EN-IN"><o:p></o:p></span></p>

<p class="MsoNormal" style="margin-top:6.4pt;margin-right:0in;margin-bottom:6.4pt;
margin-left:0in;line-height:normal;mso-outline-level:4;background:white"><u><span lang="EN-IN" style="font-size:11.5pt;font-family:&quot;Arial&quot;,sans-serif;mso-fareast-font-family:
&quot;Times New Roman&quot;;color:#555555;mso-fareast-language:EN-IN">APPLICABLE LAW AND
JURISDICTION</span></u><span lang="EN-IN" style="font-size:11.5pt;font-family:
&quot;Arial&quot;,sans-serif;mso-fareast-font-family:&quot;Times New Roman&quot;;color:#555555;
mso-fareast-language:EN-IN"><o:p></o:p></span></p>

<p class="MsoNormal" style="margin-bottom:6.4pt;line-height:normal;background:
white"><span lang="EN-IN" style="font-size:9.0pt;font-family:&quot;Arial&quot;,sans-serif;
mso-fareast-font-family:&quot;Times New Roman&quot;;color:#555555;mso-fareast-language:
EN-IN">These Terms and Conditions shall be governed by and construed in accordance with the laws of the Republic of India.</br>

Any legal proceedings arising from or relating to these Terms and Conditions shall be subject to the exclusive jurisdiction of the competent courts located in  India. <br style="mso-special-character:line-break">
<!--[if !supportLineBreakNewLine]--><br style="mso-special-character:line-break">
<!--[endif]--></span><span lang="EN-IN" style="font-size:12.0pt;font-family:&quot;Times New Roman&quot;,serif;
mso-fareast-font-family:&quot;Times New Roman&quot;;mso-fareast-language:EN-IN"><o:p></o:p></span></p>

<p class="MsoNormal" style="margin-top:6.4pt;margin-right:0in;margin-bottom:6.4pt;
margin-left:0in;line-height:normal;mso-outline-level:4;background:white"><u><span lang="EN-IN" style="font-size:11.5pt;font-family:&quot;Arial&quot;,sans-serif;mso-fareast-font-family:
&quot;Times New Roman&quot;;color:#555555;mso-fareast-language:EN-IN">TERMINATION</span></u><span lang="EN-IN" style="font-size:11.5pt;font-family:&quot;Arial&quot;,sans-serif;mso-fareast-font-family:
&quot;Times New Roman&quot;;color:#555555;mso-fareast-language:EN-IN"><o:p></o:p></span></p>

<p class="MsoNormal" style="margin-bottom:6.4pt;line-height:normal;background:
white"><span lang="EN-IN" style="font-size:9.0pt;font-family:&quot;Arial&quot;,sans-serif;
mso-fareast-font-family:&quot;Times New Roman&quot;;color:#555555;mso-fareast-language:
EN-IN">or without prior notice, if you violate these Terms and Conditions or engage in fraudulent, illegal, or unauthorized activities.</br>

Upon termination, you must immediately discontinue the use of the Website. Any rights and obligations incurred prior to termination shall survive such termination.</br>

CRTUP.IN shall not be liable for any loss or damage resulting from the suspension or termination of your access to the Website. If you are dissatisfied with the Website or any of these Terms and Conditions, your sole remedy is to discontinue using the Website.<o:p></o:p></span></p>

<p class="MsoNormal"><span lang="EN-IN"><o:p>&nbsp;</o:p></span></p></div>
</body>
</html>