<div class="copy-right"> 
    <div class="container">
        <p>© 2017 Afro Baskets. All rights reserved </p>
    </div>
</div>
<div class="footer">
    <div class="container">
        <div class="footer-info w3-agileits-info">
            <div class="col-md-4 address-left agileinfo">
                <div class="footer-logo header-logo">
                    <img src="<?php echo $this->basePath() ?>/public/images/logo-big.png"/> 
                </div>
                <ul>
                    <li><i class="fa fa-map-marker"></i> No.6, First Floor, Oxford Street Above GCB bank Net to Barclays Bank Osu, Accra Ghana.</li>
                    <!--<li><i class="fa fa-mobile"></i> 333 222 3333 </li>-->
                    <li><i class="fa fa-phone"></i> +233 553 251 740 </li>
                    <li><i class="fa fa-envelope-o"></i> <a href="mailto:example@mail.com"> mail@example.com</a></li>
                </ul> 
            </div>
            <div class="col-md-8 address-right">
                <div class="col-md-4 footer-grids">
                    <h3>Company</h3>
                    <ul>
                        <li><a href="<?=$this->basePath()?>/index.php/application/index/about">About Us</a></li>
                        <!--li><a href="<?=$this->basePath()?>/index.php/application/index/marketplace">Marketplace</a></li>  
                        <li><a href="<?=$this->basePath()?>/index.php/application/index/values">Core Values</a></li>  
                        <li><a href="<?=$this->basePath()?>/index.php/application/index/privacy">Privacy Policy</a></li-->
                    </ul>
                </div>
                <div class="col-md-4 footer-grids">
                    <h3>Services</h3>
                    <ul>
                        <li><a href="<?=$this->basePath()?>/index.php/application/index/contact">Contact Us</a></li>
						<li><a href="<?=$this->basePath()?>/index.php/application/index/termandconditions">Terms and Conditions</a></li>
                        <!--li><a href="<?=$this->basePath()?>/index.php/application/index/login">Returns</a></li> 
                        <li><a href="<?=$this->basePath()?>/index.php/application/index/faq">FAQ</a></li>
                        <li><a href="<?=$this->basePath()?>/index.php/application/index/sitemap">Site Map</a></li>
                        <li><a href="<?=$this->basePath()?>/index.php/application/index/login">Order Status</a></li-->
                    </ul> 
                </div>
                <div class="col-md-4 footer-grids">
                    <h3>Payment Methods</h3>
                    <ul>
                        <li><i class="fa fa-laptop" aria-hidden="true"></i> Net Banking</li>
                        <li><i class="fa fa-money" aria-hidden="true"></i> Cash On Delivery</li>
                        <!--li><i class="fa fa-pie-chart" aria-hidden="true"></i>EMI Conversion</li>
                        <li><i class="fa fa-gift" aria-hidden="true"></i> E-Gift Voucher</li-->
                        <li><i class="fa fa-credit-card" aria-hidden="true"></i> Debit/Credit Card</li>
                    </ul>  
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
</div>
<script src="<?php echo $this->basePath() ?>/public/js/owl.carousel.js"></script>  
<script>
    $(document).ready(function () {
        $("#owl-demo").owlCarousel({
            autoPlay: 3000, //Set AutoPlay to 3 seconds 
            items: 4,
            itemsDesktop: [640, 5],
            itemsDesktopSmall: [480, 2],
            navigation: true

        });
    });
</script>


<script src="<?php echo $this->basePath() ?>/public/js/jquery-scrolltofixed-min.js" type="text/javascript"></script>
<script>
    $(document).ready(function () {

// Dock the header to the top of the window when scrolled past the banner. This is the default behaviour.

        $('.header-two').scrollToFixed();
// previous summary up the page.

        var summaries = $('.summary');
        summaries.each(function (i) {
            var summary = $(summaries[i]);
            var next = summaries[i + 1];

            summary.scrollToFixed({
                marginTop: $('.header-two').outerHeight(true) + 10,
                zIndex: 100
            });
        });
    });
</script>
<!-- start-smooth-scrolling -->
<script type="text/javascript" src="<?php echo $this->basePath() ?>/public/js/move-top.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath() ?>/public/js/easing.js"></script>	
<script type="text/javascript" src="//maps.googleapis.com/maps/api/js?key=AIzaSyCneJAKb3o_UqKuVoIBPcTlWJLzNt6lTqo&libraries=places"></script>
<script>
function initializemap() {
          var input = document.getElementById('searchTextField');
		  var query = {componentRestrictions: {country: "gh"}};
          var autocomplete = new google.maps.places.Autocomplete(input,query);
            google.maps.event.addListener(autocomplete, 'place_changed', function () {
                var placeg = autocomplete.getPlace();
				console.log(placeg);
             $.ajax({
            method: 'POST',
            url: serverAppUrl + '/setcity',
            data: {'lattitude':placeg.geometry.location.lat(),'langitude':placeg.geometry.location.lng(),'city':placeg.formatted_address},
            headers: {'Content-Type': 'application/x-www-form-urlencoded'},
        }).success(function (response) {
		jQuery('#locatonerror').remove();
            if(response>0){
                $("#selectcity").modal('hide');
                location.reload();
            }else{
			jQuery('#searchTextField').after("<div class='error' id='locatonerror'>service not available these area. choose to another place</div>");
			}
        });        
  
            });
        }
function initializemap1() {
          var input = document.getElementById('cityname2');
		  var query = {componentRestrictions: {country: "gh"}};
          var autocomplete = new google.maps.places.Autocomplete(input,query);
            google.maps.event.addListener(autocomplete, 'place_changed', function () {
                var placeg = autocomplete.getPlace();
				console.log(placeg);
             $.ajax({
            method: 'POST',
            url: serverAppUrl + '/setcitytmp',
            data: {'lattitude':placeg.geometry.location.lat(),'langitude':placeg.geometry.location.lng(),'city':placeg.formatted_address},
            headers: {'Content-Type': 'application/x-www-form-urlencoded'},
        }).success(function (response) {
		jQuery('#locatonerror1').remove();
            if(response>0){
            }else{
			jQuery('#searchTextField').after("<div class='error' id='locatonerror1'>service not available these area. choose to another place</div>");
			}
        });        
  
            });
        }
        google.maps.event.addDomListener(window, 'load', initializemap);
		google.maps.event.addDomListener(window, 'load', initializemap1);
		</script>
<!-- //end-smooth-scrolling -->
<!-- smooth-scrolling-of-move-up -->
<script type="text/javascript">
    $(document).ready(function () {
        var defaults = {
            containerID: 'toTop', // fading element id
            containerHoverID: 'toTopHover', // fading element hover id
            scrollSpeed: 1200,
            easingType: 'linear'
        };

        $().UItoTop({easingType: 'easeOutQuart'});

    });
</script>
<!-- //smooth-scrolling-of-move-up -->
<!-- cart-js -->
<script src="<?php echo $this->basePath() ?>/public/js/minicart.js"></script>

<!-- //countdown.js -->
<!-- menu js aim -->
<script src="<?php echo $this->basePath() ?>/public/js/jquery.menu-aim.js"></script>
<script src="<?php echo $this->basePath() ?>/public/js/main.js"></script> <!-- Resource jQuery -->

<script>
    $(document).ready(function () {
        $('.owl-carousel').owlCarousel({
            loop: true,
            margin: 0,
            responsiveClass: true,
            responsive: {
                0: {
                    items: 1,
                    nav: true
                },
                480: {
                    items: 2,
                    nav: false
                },
                600: {
                    items: 3,
                    nav: false
                },
                1000: {
                    items: 5,
                    nav: true,
                    loop: false,
                    margin: 0
                }
            }
        })
    })
</script>