<!DOCTYPE html>
<html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Organ Home Page</title>
        <meta name="viewport" content="width=device-width, initial-scale=1"> 
        <meta name="description" content="Default Description">
        <meta name="keywords" content="fashion, store, E-commerce">
        <meta name="robots" content="*">
        <link rel="icon" href="#" type="image/x-icon">
        <link rel="shortcut icon" href="#" type="image/x-icon">

        <!-- CSS Style -->
        <link rel="stylesheet" type="text/css" href="<?=$this->basePath()?>/public/stylesheet/bootstrap.min.css">
        <link rel="stylesheet" type="text/css" href="<?=$this->basePath()?>/public/stylesheet/font-awesome.css" media="all">
        <link rel="stylesheet" type="text/css" href="<?=$this->basePath()?>/public/stylesheet/revslider.css" >
        <link rel="stylesheet" type="text/css" href="<?=$this->basePath()?>/public/stylesheet/owl.carousel.css">
        <link rel="stylesheet" type="text/css" href="<?=$this->basePath()?>/public/stylesheet/owl.theme.css">
        <link rel="stylesheet" type="text/css" href="<?=$this->basePath()?>/public/stylesheet/jquery.bxslider.css">
        <link rel="stylesheet" type="text/css" href="<?=$this->basePath()?>/public/stylesheet/jquery.mobile-menu.css">
        <link rel="stylesheet" type="text/css" href="<?=$this->basePath()?>/public/stylesheet/style.css" media="all">
        <link rel="stylesheet" type="text/css" href="<?=$this->basePath()?>/public/stylesheet/responsive.css" media="all">

        <link href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,700italic,400,600,700,800' rel='stylesheet' type='text/css'>
        <link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
        <link href='http://fonts.googleapis.com/css?family=Roboto+Slab:400,700' rel='stylesheet' type='text/css'>

        
        
        
<script>
    var serverAppUrl = '<?php echo $GLOBALS['SITE_APP_URL']; ?>';
    var city = 0;
	function opencity(){
	$('#selectcity').modal({
        backdrop: 'static',
        keyboard: false
    });
	}
</script>
        
        
        
        
        
             
        <!--javascript-->
        <script type="text/javascript" src="<?=$this->basePath()?>/public/js/jquery.min.js"></script>
        <script type="text/javascript" src="<?=$this->basePath()?>/public/js/bootstrap.min.js"></script>
        <script type="text/javascript" src="<?=$this->basePath()?>/public/js/angular.min.js"></script>
        <script type="text/javascript" src="<?=$this->basePath()?>/public/js/ui-bootstrap-tpls-0.12.1.min.js"></script>
        <script type="text/javascript" src="<?=$this->basePath()?>/public/js/parallax.js"></script>
        <script type="text/javascript" src="<?=$this->basePath()?>/public/js/revslider.js"></script>
        <script type="text/javascript" src="<?=$this->basePath()?>/public/js/common.js"></script>
        <script type="text/javascript" src="<?=$this->basePath()?>/public/js/custom-common.js"></script>
        <script type="text/javascript" src="<?=$this->basePath()?>/public/js/jquery.bxslider.min.js"></script>
        <script type="text/javascript" src="<?=$this->basePath()?>/public/js/owl.carousel.min.js"></script>
        <script type="text/javascript" src="<?=$this->basePath()?>/public/js/jquery.mobile-menu.min.js"></script>
    </head>
    <body>
        <div id="mobile-menu">
            <ul>
                <li>
                    <div class="home"><a href="#"><i class="icon-home"></i>Home</a> </div>
                </li>
                <li><a href="#">Pages</a>
                    <ul>
                        <li><a href="grid.html">Grid</a></li>
                        <li> <a href="list.html">List</a></li>
                        <li> <a href="product-detail.html">Product Detail</a></li>
                        <li> <a href="shopping-cart.html">Shopping Cart</a></li>
                        <li><a href="checkout.html">Checkout</a>
                            <ul>
                                <li><a href="checkout-method.html">Checkout Method</a></li>
                                <li><a href="checkout-billing-info.html">Checkout Billing Info</a></li>
                            </ul>
                        </li>
                        <li> <a href="wishlist.html">Wishlist</a></li>
                        <li> <a href="dashboard.html">Dashboard</a></li>
                        <li> <a href="multiple-addresses.html">Multiple Addresses</a></li>
                        <li> <a href="about-us.html">About us</a></li>
                        <li><a href="blog.html">Blog</a>
                            <ul>
                                <li><a href="blog-detail.html">Blog Detail</a></li>
                            </ul>
                        </li>
                        <li><a href="contact-us.html">Contact us</a></li>
                        <li><a href="404error.html">404 Error Page</a></li>
                    </ul>
                </li>
                <li><a href="grid.html">Salads?</a>
                    <ul>
                        <li><a href="grid.html"><span>Bread Salads?</span></a>         
                            <ul>
                                <li> <a href="grid.html"><span>Cappon Magro</span></a> </li>
                                <li> <a href="grid.html"><span>Dakos</span></a> </li>
                                <li> <a href="grid.html"><span>Fattoush</span></a> </li>
                                <li> <a href="grid.html"><span>Panzanella</span></a> </li>
                            </ul>
                        </li>
                        <li> <a href="grid.html"><span>Fruit Salads?</span></a>
                            <ul>
                                <li> <a href="grid.html"><span>Candle Salad</span></a> </li>
                                <li> <a href="grid.html"><span>Frogeye Salad</span></a> </li>
                                <li> <a href="grid.html"><span>Green Papaya Salad</span></a> </li>
                                <li> <a href="grid.html"><span>Waldorf salad</span></a> </li>
                            </ul>
                        </li>
                        <li> <a href="grid.html"><span>Salad Dressings</span></a>
                            <ul>
                                <li> <a href="grid.html"><span>Louis Dressings</span></a> </li>
                                <li> <a href="grid.html"><span>French Dressings</span></a> </li>
                                <li> <a href="grid.html"><span>Gingner Dressings</span></a> </li>
                                <li> <a href="grid.html"><span>Italian Dressings</span></a> </li>
                            </ul>         
                        </li>       
                        <li> <a href="grid.html"><span>Leaf Vegetable</span></a>          
                            <ul>
                                <li> <a href="grid.html"><span>Fenugreek</span></a> </li>            
                                <li> <a href="grid.html"><span>Spinach</span></a> </li>            
                                <li> <a href="grid.html"><span>Malva</span></a> </li>            
                                <li> <a href="grid.html"><span>Cabbage</span></a> </li>            
                            </ul>        
                        </li>
                    </ul>
                </li>
                <li><a href="grid.html">Soups</a>
                    <ul>
                        <li> <a href="grid.html"><span>Cold Soups</span></a>
                            <ul>
                                <li> <a href="grid.html"><span>Red Bean Soup</span></a> </li>
                                <li> <a href="grid.html"><span>Fruit Soup</span></a> </li>
                                <li> <a href="grid.html"><span>Naengguk</span></a> </li>
                                <li> <a href="grid.html"><span>Borscht</span></a> </li>
                            </ul>
                        </li>
                        <li> <a href="grid.html"><span>Cream Soups</span></a>
                            <ul>
                                <li> <a href="grid.html"><span>Chowder</span></a> </li>
                                <li> <a href="grid.html"><span>Asparagus Soup</span></a> </li>
                                <li> <a href="grid.html"><span>Broccoli Soup</span></a> </li>
                                <li> <a href="grid.html"><span>Mushroom Soup</span></a> </li>
                            </ul>
                        </li>
                        <li> <a href="grid.html"><span>Vegitable Soups</span></a>
                            <ul>
                                <li> <a href="grid.html"><span>French Onion Soup</span></a> </li>
                                <li> <a href="grid.html"><span>Leek Soup</span></a> </li>
                                <li> <a href="grid.html"><span>Minestrone</span></a> </li>
                                <li> <a href="grid.html"><span>Spring Soup</span></a> </li>
                            </ul>
                        </li>
                        <li> <a href="grid.html"><span>Bean Soups</span></a>
                            <ul>
                                <li> <a href="grid.html"><span>Bouneschlupp</span></a> </li>
                                <li> <a href="grid.html"><span>J󫡩 Bean Soup</span></a> </li>
                                <li> <a href="grid.html"><span>Kwati Soup</span></a> </li>
                                <li> <a href="grid.html"><span>Senate bean</span></a> </li>
                            </ul>
                        </li>
                        <li> <a href="grid.html"><span>Bread Soups</span></a>
                            <ul>
                                <li> <a href="grid.html"><span>Tomato Soup</span></a> </li>
                                <li> <a href="grid.html"><span>Manchow Soup</span></a> </li>
                                <li> <a href="grid.html"><span>Sweet Corn Soup</span></a> </li>
                                <li> <a href="grid.html"><span>Shorba Soup</span></a> </li>
                            </ul>
                        </li>
                        <li> <a href="grid.html"><span>Chinese Soups</span></a>
                            <ul>
                                <li> <a href="grid.html"><span>Hot & Sour</span></a> </li>
                                <li> <a href="grid.html"><span>Noodle Soup</span></a> </li>
                                <li> <a href="grid.html"><span>Corn Crab Soup</span></a> </li>
                                <li> <a href="grid.html"><span>Sago Soup</span></a> </li>
                            </ul>
                        </li>
                    </ul>
                </li>
                <li><a href="grid.html">Fast Food</a>
                    <ul>
                        <li> <a href="grid.html"><span>Indian</span></a>
                            <ul>
                                <li> <a href="grid.html"><span>Aloo Chaat</span></a> </li>
                                <li> <a href="grid.html"><span>Batata Vada</span></a> </li>
                                <li> <a href="grid.html"><span>Kachori</span></a> </li>
                                <li> <a href="grid.html"><span>Panipuri</span></a> </li>
                            </ul>
                        </li>
                        <li> <a href="grid.html"><span>Pizza</span></a>
                            <ul>
                                <li> <a href="grid.html"><span>Greek Pizza</span></a> </li>
                                <li> <a href="grid.html"><span>Pizza Rolls</span></a> </li>
                                <li> <a href="grid.html"><span>Grilled Pizza</span></a> </li>
                                <li> <a href="grid.html"><span>Pizza Strips</span></a> </li>
                            </ul>
                        </li>
                        <li> <a href="grid.html"><span>McDonald's</span></a>
                            <ul>
                                <li> <a href="grid.html"><span>Kiwiburger</span></a> </li>
                                <li> <a href="grid.html"><span>Happy Meal</span></a> </li>
                                <li> <a href="grid.html"><span>McMuffin</span></a> </li>
                                <li> <a href="grid.html"><span>McGriddles</span></a> </li>
                            </ul>
                        </li>
                        <li> <a href="grid.html"><span>Wendy's Foods</span></a>
                            <ul>
                                <li> <a href="grid.html"><span>Bacon Deluxe</span></a> </li>
                                <li> <a href="grid.html"><span>Baconator</span></a> </li>
                                <li> <a href="grid.html"><span>Frescata</span></a> </li>
                                <li> <a href="grid.html"><span>Frosty</span></a> </li>
                            </ul>
                        </li>
                        <li> <a href="grid.html"><span>Burger King</span></a>
                            <ul>
                                <li> <a href="grid.html"><span>Big King</span></a> </li>
                                <li> <a href="grid.html"><span>TenderCrisp</span></a> </li>
                                <li> <a href="grid.html"><span>Whopper</span></a> </li>
                                <li> <a href="grid.html"><span>Kuro Burger</span></a> </li>
                            </ul>
                        </li>
                        <li> <a href="grid.html"><span>Sandwiches</span></a>
                            <ul>
                                <li> <a href="grid.html"><span>Hamburgers</span></a> </li>
                                <li> <a href="grid.html"><span> Hot Dogs?</span></a> </li>
                                <li> <a href="grid.html"><span>American Sandwiches</span></a> </li>
                                <li> <a href="grid.html"><span>Chilean Sandwiches</span></a> </li>
                            </ul>
                        </li>
                    </ul>
                </li>   
                <li><a href="grid.html">Sandwiches?</a></li>
                <li><a href="contact-us.html">Contact Us</a></li>
            </ul>
        </div>    
        <div id="page"  ng-app="app">
            <header>
                <div class="header-banner">
                    <div class="assetBlock">
                        <div style="height: 20px; overflow: hidden;" id="slideshow">
                            <p style="display: block;">HOT DAYS! - <span>50%</span> GET READY FOR SUMMER! &gt;</p>
                            <p style="display: none;">SALE UP TO <span>40%</span> HURRY LIMITED OFFER! &gt;</p>
                        </div>
                    </div>
                </div> 
                <div id="header">
                    <div class="header-container container">
                        <div class="row">
                            <div class="logo"> <a href="<?=$this->basepath()?>">
                                    <div><img src="<?=$this->basepath()?>/public/images/logo-big.png" alt="Organ Store"></div>
                                </a> </div>
                           
                            <div class="fl-nav-menu">

                                <nav>
                                    <div class="mm-toggle-wrap">
                                        <div class="mm-toggle"><i class="icon-align-justify"></i><span class="mm-label">Menu</span> </div>
                                    </div>
                                    
                                    <div class="nav-inner">
                                        <!-- BEGIN NAV -->
                                        <ul id="nav" class="hidden-xs">
                                        
                                            <?php
                                            $counter = 0;
                                            foreach ($GLOBALS['category_list']['data'] as $category){
                                                $categoryImageDetails = $GLOBALS['category_list']['images'][$category['id']][0];
                                                $categoryImagePath = $GLOBALS['category_list']['imageRootPath'].'/'.$categoryImageDetails['type'].'/'.$categoryImageDetails['image_id'].'/'.$categoryImageDetails['image_name'];                                                
                                                if (!empty($category['category_name'])) {
                                                    $counter++;
                                                    if ($counter == 6) {
                                                        break;
                                                    }
                                                    ?> 
                                                    <li class="mega-menu"> 
                                                        <a class="level-top" href="<?=$this->basePath()?>/index.php/application/index/product?id=<?=$category['id']?>">
                                                            <span>
                                                                <?php
                                                                echo $category['category_name'];
                                                                ?>
                                                            </span>
                                                        </a>
                                                        <?php
                                                        if(!empty($category['child'])) {
                                                        ?>
                                                        <div class="level0-wrapper dropdown-6col" style="left: 0px; display: none;">
                                                            <div class="container">
                                                                <div class="level0-wrapper2">
                                                                    <div class="col-1">
                                                                        <div class="nav-block nav-block-center">
                                                                            <!--mega menu-->
                                                                            <ul class="level0">
                                                                                <?php
                                                                                foreach($category['child'] as $childcategory){
                                                                                 ?>  
                                                                                <li class="level3 nav-6-1 parent item"> <a href="<?=$this->basePath()?>/index.php/application/index/product?id=<?=$childcategory['id']?>"><span><?=$childcategory['category_name']?></span></a>
                                                                                    
                                                                                </li>
                                                                                <?php
                                                                                }
                                                                                ?>
                                                                                
                                                                            </ul>
                                                                            <!--level0-->
                                                                        </div>
                                                                        <!--nav-block nav-block-center-->
                                                                    </div>
                                                                    <!--col-1-->
                                                                    <div class="col-2">
                                                                        
                                                                        
                                                                        <div class="menu_image"><a title="" href="grid.html"><img alt="menu_image" src="<?=$categoryImagePath?>"></a></div>

                                                                    </div>
                                                                    <!--col-2-->
                                                                </div>
                                                                <!--level0-wrapper2-->
                                                            </div>
                                                            <!--container-->
                                                        </div> 
                                                                                
                                                        <?php
                                                        }
                                                        ?>
                                                    </li>
                                                    <?php
                                                }
                                            }
                                            ?>
                                        </ul>
                                        <!--nav-->
                                    </div>
                                </nav>
                            </div>




                            <!--row-->


                            <div class="fl-header-right">
                                <div class="fl-links">
                                    <div class="no-js"> <a title="Company" class="clicker"></a>
                                        <div class="fl-nav-links">
                                            <ul class="links">
                                            <?php
                                                if(!empty($GLOBALS['user'])){
                                            ?>
                                                <li><a href="<?=$this->basePath()?>/index.php/application/index/editprofile" title="My Account">My Account</a></li>                                                                                                
                                                <li><a href="<?=$this->basePath()?>/index.php/application/index/changepassword">Change Password</a></li> 
                                                <li><a href="<?=$this->basePath()?>/index.php/application/index/currentorder">My Order</a></li>
                                                <li><a href="<?=$this->basePath()?>/index.php/application/index/checkout" title="Checkout">Checkout</a></li>
                                                <li><a href="<?=$this->basePath()?>/index.php/application/index/logout">Log-out</a></li> 
                                                 <?php }else{ ?>
                                            </ul>
                                            <ul class="links">
                                                 <li><a href="<?=$this->basePath()?>/index.php/application/index/signup">Signup</a></li>
                                                <li class="last"><a href="<?=$this->basePath()?>/index.php/application/index/login" title="Login"><span>Login</span></a></li>
                                            </ul>
                                            <?php }?>
                                        </div>
                                    </div>
                                </div>
                                <div class="fl-cart-contain" ng-controller="cartcontroller">
                                    <div class="mini-cart">
                                        <div class="basket"> <a href="javascript:void(0);"><span> {{totalItemInCart}} </span></a> </div>
                                        <div class="fl-mini-cart-content" style="display: none;">
                                            <div class="block-subtitle">
                                                <div class="top-subtotal">{{totalItemInCart}} items, <span class="price"> </span> </div>
                                                <!--top-subtotal-->
                                                <!--pull-right-->
                                            </div>
                                            <!--block-subtitle-->
                                            <ul class="mini-products-list" id="cart-sidebar">
                                                <li class="item first" ng-repeat="cartItem in cartResponse.data">
                                                    
                                                    <div class="item-inner">
                                                        <a class="product-image" href="javascript:void(0);">
                                                            <img src="{{cartResponse.imageRootPath}}/{{cartResponse.productDetails.productImageData[cartResponse.productDetails.data[cartItem.merchant_inventry_id].product_id][0].type}}/{{cartResponse.productDetails.data[cartItem.merchant_inventry_id].product_id}}/{{cartResponse.productDetails.productImageData[cartResponse.productDetails.data[cartItem.merchant_inventry_id].product_id][0].image_name}}"/>
                                                        </a>
                                                        <div class="product-details">
                                                            <div class="access">
                                                                <a class="btn-remove1" title="Remove This Item" href="javascript:void(0);">Remove</a> <a class="btn-edit" title="Edit item" href="#"><i class="icon-pencil"></i><span class="hidden">Edit item</span></a> 
                                                            </div>
                                                            <!--access-->
                                                            <strong>{{cartItem.number_of_item}}</strong> x <span class="price">GHC {{cartResponse.productDetails.data[cartItem.merchant_inventry_id].price}}</span>
                                                            
                                                            <p class="product-name"><a href="javascript::void(0)">{{cartItem.item_name}}</a></p>
                                                        </div>
                                                    </div>
                                                </li>
                                            </ul>
                                            <div class="actions">
                                                <button class="btn-checkout" title="Checkout" type="button" onClick="window.location = checkout.html"><span>Checkout</span></button>
                                            </div>
                                            <!--actions-->
                                        </div>
                                        <!--fl-mini-cart-content-->
                                    </div>
                                </div>
                                <!--mini-cart-->
                                <div class="collapse navbar-collapse">
                                    <form class="navbar-form" role="search">
                                        <div class="input-group">
                                            <input type="text" class="form-control" placeholder="Search">
                                            <span class="input-group-btn">
                                                <button type="submit" class="search-btn"> <span class="glyphicon glyphicon-search"> <span class="sr-only">Search</span> </span> </button>
                                            </span> </div>
                                    </form>
                                </div>
                                <!--links-->
                            </div>
                        </div>
                    </div>	
                </div>

            </header>