<head>
    <title>Afro Basket an E-commerce Online Shopping Category</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Afro Basket Responsive web template" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false);
        function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!-- Custom Theme files -->
    <link href="<?php echo $this->basePath() ?>/public/css/bootstrap.css" rel="stylesheet" type="text/css" media="all" />
    <link href="<?php echo $this->basePath() ?>/public/css/style.css" rel="stylesheet" type="text/css" media="all" /> 
    <link href="<?php echo $this->basePath() ?>/public/css/menu.css" rel="stylesheet" type="text/css" media="all" /> <!-- menu style --> 
    <link href="<?php echo $this->basePath() ?>/public/css/ken-burns.css" rel="stylesheet" type="text/css" media="all" /> <!-- banner slider --> 
    <link href="<?php echo $this->basePath() ?>/public/css/animate.min.css" rel="stylesheet" type="text/css" media="all" /> 
    <link href="<?php echo $this->basePath() ?>/public/css/owl.carousel.css" rel="stylesheet" type="text/css" media="all"> <!-- carousel slider -->  
    <link href="<?php echo $this->basePath() ?>/public/css/slider.css" rel="stylesheet" type="text/css" media="all">    
    <link href="<?php echo $this->basePath() ?>/public/css/location.css" rel="stylesheet" type="text/css" media="all">   
     <link href="<?php echo $this->basePath() ?>/public/css/jquery-ui.css" rel="stylesheet" type="text/css" media="all">   
    <!-- //Custom Theme files -->
    <!-- font-awesome icons -->
    <link href="<?php echo $this->basePath() ?>/public/css/font-awesome.css" rel="stylesheet"> 
    <!-- //font-awesome icons -->
    <!-- js -->
    <!-- //js --> 
    <!-- web-fonts -->
    <!-- web-fonts --> 
    <script src="<?php echo $this->basePath() ?>/public/js/bootstrap.min.js"></script>
    <style> 
        .owl-nav{position: absolute; top: 0; left: 0;width: 100%; margin: 0;}
        .owl-carousel .owl-nav .owl-prev{position: absolute;left: -5px; top: 0; height: 300px; width: 30px; margin: 0; }
        .owl-carousel .owl-nav .owl-next{position: absolute;right: 0px; top: 0; height: 300px; width: 30px; margin: 0;}
        .owl-carousel .owl-item .merchant img{width: 80%;}
        .merchant_name{font-size: 16px;}
    </style>
</head>
<div ng-app="app">
<div class="header">
    <div class="w3ls-header"><!--header-one--> 
        <div class="w3ls-header-left">
            <p>SALE UP TO 70% OFF. USE CODE "SALE70%" . <a href="<?= $this->basePath() ?>/application/index/products">SHOP NOW</a></p>
        </div>                
        <div class="clearfix"> </div> 
    </div>
    <div class="header-two"> 
        <div class="container no-lpad no-rpad">
            <div class="header-logo">
                <a href="<?=$this->basePath()?>">
                <img src="<?php echo $this->basePath() ?>/public/images/logo-big.png" alt="logo"/> 
                </a>
            </div>	
            <div class="header-city">
                <select class="form-control select2" style="width: 100%;">
                    <?php
                        foreach ($GLOBALS['city_list'] as $key => $value) {
                            echo'<option value="'.$value['id'].'">'.$value['city_name'].'</option>';
                        }
                    ?>
                    </select>
                <!--<a class="cd-dropdown-trigger" href="#" id="city-link"  style="color:#000000;">Select Your City</a>-->
            </div>
            <div class="header-search">
                <form action="#" method="post">
                    <input type="search" name="Search" placeholder="Search for a Product..." required="">
                    <button type="submit" class="btn btn-default" aria-label="Left Align">
                        <i class="fa fa-search" aria-hidden="true"> </i>
                    </button>
                </form>
            </div>
            <div class="header-cart"> 
                <div class="dropdown my-account">
                    <?php
                        if(!empty($GLOBALS['user'])){
                    ?>
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-user" aria-hidden="true"></i> My Account <b class="caret"></b></a>
                    <ul class="dropdown-menu multi-column columns-3 pull-right" style="padding:0px 20px;">
                        <div class="row">
                            <div class="multi-gd-img">
                                <ul class="multi-column-dropdown">
                                    <li><a href="#">Account Setting</a></li>
                                    <li><a href="#">My Order</a></li>
                                    <li><a href="#">Past Order </a></li>
                                    <li><a href="<?=$this->basePath()?>/application/index/changepassword">Change Password</a></li> 
                                    <li><a href="<?=$this->basePath()?>/application/index/logout">Log-out</a></li> 
                                </ul>
                            </div>
                        </div>
                    </ul>
                    <?php }else{ ?>
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-user" aria-hidden="true"></i> Your Account  <b class="caret"></b></a>
                    <ul class="dropdown-menu multi-column columns-3 pull-right" style="padding:0px 20px;">
                        <div class="row">
                            <div class="multi-gd-img">
                                <ul class="multi-column-dropdown">
                                    <li><a href="<?=$this->basePath()?>/application/index/signup">Signup</a></li>
                                    <li><a href="<?=$this->basePath()?>/application/index/login">Login</a></li>
                                </ul>
                            </div>
                        </div>
                    </ul>
                    <?php }?>
                </div>
                <div class="cart" ng-controller="cartcontroller"> 
                    <a ng-click="cartList()" class="w3view-cart" id="w3view-cart"><i class="fa fa-cart-arrow-down" aria-hidden="true"></i></a>
                     My Cart
                    <ul class="dropdown-menu  multi-column columns-5 pull-right w3view-cart-menu">
                        <div class="row">
                            <a href="#" class="w3view-cart-close">X</a>
                            <div class="cart-gd-img">
                                <ul class="cart-column-dropdown">
                                    <li ng-repeat="cartItem in cartResponse.data">
                                        <img src="{{cartResponse.imageRootPath}}/{{cartResponse.productDetails.productImageData[cartResponse.productDetails.data[cartItem.merchant_inventry_id].product_id][0].type}}/{{cartResponse.productDetails.data[cartItem.merchant_inventry_id].product_id}}/{{cartResponse.productDetails.productImageData[cartResponse.productDetails.data[cartItem.merchant_inventry_id].product_id][0].image_name}}"/>
                                        <span class="title">{{cartItem.item_name}}<br>
                                            <span class="item-quant">Item:  {{cartItem.number_of_item}}</span>
                                            <i class="fa fa-plus green-text" ng-click="addToCart(cartItem.merchant_inventry_id, cartItem.item_name, 'add', 1)"></i> <i class="fa fa-minus red-text" ng-click="addToCart(cartItem.merchant_inventry_id, cartItem.item_name, 'delete', 1)"></i>
                                        </span> <span class="price">GHC {{cartResponse.productDetails.data[cartItem.merchant_inventry_id].price}}</span>
                                    </li>
                                    <li ng-if="cartResponse.data">
                                        <a class="button conti" href="<?= $this->basePath() ?>">Continue Shopping</a> 
					<a class="button proceed" href="<?= $this->basePath() ?>/application/index/checkout" class="cart" id="cart" >Proceed To Checkout</a>
				  </li>                                    
                                </ul>
                            </div>	
                        </div>
                    </ul>
                </div>
                <div class="clearfix"> </div> 
            </div> 
            <div class="clearfix"> </div>
        </div>		
    </div><!-- //header-two -->
    <!-- navigation -->
    <div class="navigation-agileits">
        <div class="container">
            <nav class="navbar navbar-default">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header nav_2">
                    <button type="button" class="navbar-toggle collapsed navbar-toggle1" data-toggle="collapse" data-target="#bs-megadropdown-tabs">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div> 
                <div class="collapse navbar-collapse" id="bs-megadropdown-tabs">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?= $this->basePath() ?>/application/index/index" class="act">Home</a></li>	
                        <!-- Mega Menu -->
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Groceries<b class="caret"></b></a>
                            <ul class="dropdown-menu multi-column columns-3">
                                <div class="row">
                                    <div class="multi-gd-img">
                                        <ul class="multi-column-dropdown">
                                            <h6>All Groceries</h6>
                                            <li><a href="<?= $this->basePath() ?>/application/index/product">Dals & Pulses</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/product">Almonds</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/product">Cashews</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/product">Dry Fruit</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/product"> Mukhwas </a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/product">Rice & Rice Products</a></li>
                                        </ul>
                                    </div>	

                                </div>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Household<b class="caret"></b></a>
                            <ul class="dropdown-menu multi-column columns-3">
                                <div class="row">
                                    <div class="multi-gd-img">
                                        <ul class="multi-column-dropdown">
                                            <h6>All Household</h6>
                                            <li><a href="<?= $this->basePath() ?>/application/index/product">Cookware</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/product">Dust Pans</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/product">Scrubbers</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/product">Dust Cloth</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/product"> Mops </a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/product">Kitchenware</a></li>
                                        </ul>
                                    </div>


                                </div>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Personal Care<b class="caret"></b></a>
                            <ul class="dropdown-menu multi-column columns-3">
                                <div class="row">
                                    <div class="multi-gd-img">
                                        <ul class="multi-column-dropdown">
                                            <h6>Baby Care</h6>
                                            <li><a href="<?= $this->basePath() ?>/application/index/product">Baby Soap</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/product">Baby Care Accessories</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/product">Baby Oil & Shampoos</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/product">Baby Creams & Lotion</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/product"> Baby Phouseholdowder</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/product">Diapers & Wipes</a></li>
                                        </ul>
                                    </div>

                                </div>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Packaged Foods<b class="caret"></b></a>
                            <ul class="dropdown-menu multi-column columns-3">
                                <div class="row">
                                    <div class="multi-gd-img">
                                        <ul class="multi-column-dropdown">
                                            <h6>All Accessories</h6>
                                            <li><a href="<?= $this->basePath() ?>/application/index/product">Baby Food</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/product">Dessert Items</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/product">Biscuits</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/product">Breakfast Cereals</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/product"> Canned Food </a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/product">Chocolates & Sweets</a></li>
                                        </ul>
                                    </div>


                                </div>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Beverages<b class="caret"></b></a>
                            <ul class="dropdown-menu multi-column columns-3">
                                <div class="row">
                                    <div class="multi-gd-img">
                                        <ul class="multi-column-dropdown">
                                            <h6>Tea & Coeffe</h6>
                                            <li><a href="<?= $this->basePath() ?>/application/index/product">Green Tea</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/product">Ground Coffee</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/product">Herbal Tea</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/product">Instant Coffee</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/product"> Tea </a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/product">Tea Bags</a></li>
                                        </ul>
                                    </div>

                                </div>
                            </ul>
                        </li>
                        <li><a href="<?= $this->basePath() ?>/application/index/product">Gourmet</a></li>
                        <li><a href="<?= $this->basePath() ?>/application/index/product">Offers</a></li>
                        <li><a href="<?= $this->basePath() ?>/application/index/contact">Contact</a></li>
                    </ul>
                </div>
            </nav>
        </div>
    </div>

    <!-- //navigation -->

    <div class="header-three hide"><!-- header-three -->
        <div class="container">
            <div class="menu">
                <div class="cd-dropdown-wrapper">
                    <a class="cd-dropdown-trigger" href="#0">Select Your City</a>
                    <nav class="cd-dropdown"> 
                        <a href="#0" class="cd-close">Close</a>
                        <ul class="cd-dropdown-content"> 
                            <li><a href="offers">Today's Offers</a></li>
                            <li class="has-children">
                                <a href="#">Electronics</a> 
                                <ul class="cd-secondary-dropdown is-hidden">
                                    <li class="go-back"><a href="#">Menu</a></li>
                                    <li class="see-all"><a href="<?= $this->basePath() ?>/application/index/products">All Electronics</a></li>
                                    <li class="has-children">
                                        <a href="#">MOBILE PHONES</a>  
                                        <ul class="is-hidden"> 
                                            <li class="go-back"><a href="#">All Electronics</a></li> 
                                            <li class="has-children">
                                                <a href="#0">SmartPhones</a> 
                                                <ul class="is-hidden"> 
                                                    <li class="go-back"><a href="#"> </a></li>
                                                    <li><a href="<?= $this->basePath() ?>/application/index/products">Android</a></li>
                                                    <li><a href="<?= $this->basePath() ?>/application/index/products">Windows</a></li>
                                                    <li><a href="<?= $this->basePath() ?>/application/index/products">Black berry</a></li>
                                                </ul>
                                            </li>
                                            <li> <a href="<?= $this->basePath() ?>/application/index/products">IPhones</a> </li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Tablets</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">IPad</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Feature Phones</a></li> 
                                        </ul>
                                    </li> 
                                    <li class="has-children">
                                        <a href="#">LARGE APPLIANCES</a> 
                                        <ul class="is-hidden"> 
                                            <li class="go-back"><a href="#">All Electronics </a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Refrigerators</a></li> 
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Washing Machine</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Office Technology</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Air conditioner</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Home Automation</a></li>
                                        </ul>
                                    </li> 
                                    <li class="has-children">
                                        <a href="#">ENTERTAINMENT</a> 
                                        <ul class="is-hidden"> 
                                            <li class="go-back"><a href="#">All Electronics</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Tv & Accessories</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Digital Camera</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Gaming</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Home Audio & Theater</a></li>
                                            <li class="has-children">
                                                <a href="#">Computer</a>
                                                <ul class="is-hidden">
                                                    <li class="go-back"><a href="#"> </a></li> 
                                                    <li><a href="<?= $this->basePath() ?>/application/index/products">Laptop </a></li>
                                                    <li><a href="<?= $this->basePath() ?>/application/index/products">Gaming PC</a></li>
                                                    <li><a href="<?= $this->basePath() ?>/application/index/products">Monitors</a></li>
                                                    <li><a href="<?= $this->basePath() ?>/application/index/products">Networking</a></li>
                                                    <li><a href="<?= $this->basePath() ?>/application/index/products">Printers & Supplies</a></li>
                                                    <li><a href="<?= $this->basePath() ?>/application/index/products">Accessories</a></li>
                                                </ul>
                                            </li> 
                                        </ul>
                                    </li> 
                                    <li class="has-children">
                                        <a href="#">HOME APPLIANCES</a> 
                                        <ul class="is-hidden">
                                            <li class="go-back"><a href="#0">All Electronics </a></li>
                                            <li class="has-children"><a href="#">Kitchen appliances</a>
                                                <ul class="is-hidden">
                                                    <li class="go-back"><a href="#0"> </a></li>
                                                    <li><a href="<?= $this->basePath() ?>/application/index/products">Rice Cookers</a></li>
                                                    <li><a href="<?= $this->basePath() ?>/application/index/products">Mixer Juicer</a></li>
                                                    <li><a href="<?= $this->basePath() ?>/application/index/products">Grinder</a></li>
                                                    <li><a href="<?= $this->basePath() ?>/application/index/products">Blenders & Choppers</a></li>
                                                    <li><a href="<?= $this->basePath() ?>/application/index/products">Microwave Oven</a></li>
                                                    <li><a href="<?= $this->basePath() ?>/application/index/products">Food Processors</a></li>
                                                </ul>
                                            </li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Purifiers</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Geysers</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Gas Stove</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Vacuum Cleaner</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Sewing Machine</a></li> 
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Heaters & Fans</a></li>
                                        </ul>
                                    </li>
                                    <li class="has-children">
                                        <a href="#">SMALL DEVICES</a> 
                                        <ul class="is-hidden"> 
                                            <li class="go-back"><a href="#0">All Electronics </a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Wifi Dongle</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Router & Modem</a></li>
                                            <li class="has-children"><a href="#">Storage Devices</a>
                                                <ul class="is-hidden">
                                                    <li class="go-back"><a href="#0"> </a></li>
                                                    <li><a href="<?= $this->basePath() ?>/application/index/products">Cloud Storage</a></li>
                                                    <li><a href="<?= $this->basePath() ?>/application/index/products">Hard Disk</a></li>
                                                    <li><a href="<?= $this->basePath() ?>/application/index/products">SSD</a></li>
                                                    <li><a href="<?= $this->basePath() ?>/application/index/products">Pen Drive</a></li>
                                                    <li><a href="<?= $this->basePath() ?>/application/index/products">Memory card</a></li> 
                                                    <li><a href="<?= $this->basePath() ?>/application/index/products">Security Devices</a></li> 
                                                </ul>
                                            </li> 
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Office Supplies</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Cut the Cable</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Auto Electronics</a></li>  
                                        </ul>
                                    </li>
                                    <li class="has-children">
                                        <a href="#">PERSONAL CARE</a> 
                                        <ul class="is-hidden"> 
                                            <li class="go-back"><a href="#0">All Electronics </a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Epilator</a></li> 
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Hair Styler</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Trimmer & Shaver</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Health Care</a></li> 
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">cables</a></li>
                                        </ul>
                                    </li>
                                </ul> <!-- .cd-secondary-dropdown --> 
                            </li> <!-- .has-children -->
                            <li class="has-children">
                                <a href="#">Fashion Store</a> 
                                <ul class="cd-secondary-dropdown is-hidden">
                                    <li class="go-back"><a href="#">Menu</a></li>
                                    <li class="see-all"><a href="<?= $this->basePath() ?>/application/index/products1">All Fashion Stores</a></li>
                                    <li class="has-children">
                                        <a href="#">GIRLS' CLOTHING</a> 
                                        <ul class="is-hidden">  
                                            <li class="go-back"><a href="#">All Fashion Stores</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products1">Ethnic wear </a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products1">Maternity wear</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products1">inner & nightwear </a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products1">casual wear </a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products1">formal wear</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products1">Sports wear</a></li>
                                        </ul>
                                    </li> 
                                    <li class="has-children">
                                        <a href="#">BOYS' CLOTHING</a> 
                                        <ul class="is-hidden">  
                                            <li class="go-back"><a href="#">All Fashion Stores</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products1">Jeans</a></li>  
                                            <li><a href="<?= $this->basePath() ?>/application/index/products1">Casual wear</a></li> 
                                            <li><a href="<?= $this->basePath() ?>/application/index/products1">Shorts</a></li> 
                                            <li><a href="<?= $this->basePath() ?>/application/index/products1">T-Shirts & Polos</a></li> 
                                            <li><a href="<?= $this->basePath() ?>/application/index/products1">Trousers & Chinos</a></li> 
                                        </ul>
                                    </li> 
                                    <li class="has-children">
                                        <a href="#">JACKETS</a> 
                                        <ul class="is-hidden">
                                            <li class="go-back"><a href="#">All Fashion Stores</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products1">Blazers</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products1">Bomber jackets</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products1">Denim Jackets</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products1">Duffle Coats</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products1">Leather Jackets</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products1">Parkas</a></li>
                                        </ul>
                                    </li> 
                                    <li class="has-children">
                                        <a href="#">ACCESSORIES </a> 
                                        <ul class="is-hidden"> 
                                            <li class="go-back"><a href="#">All Fashion Stores</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products1">Watches </a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products1">Eyewear </a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products1">Jewellery </a></li>
                                            <li class="has-children">
                                                <a href="#">Footwear </a>  
                                                <ul class="is-hidden">
                                                    <li class="go-back"><a href="#"> </a></li>
                                                    <li><a href="<?= $this->basePath() ?>/application/index/products1">Ethnic</a></li>  
                                                    <li><a href="<?= $this->basePath() ?>/application/index/products1">Casual wear</a></li>
                                                    <li><a href="<?= $this->basePath() ?>/application/index/products1">Sports Shoes</a></li>
                                                    <li><a href="<?= $this->basePath() ?>/application/index/products1">Boots</a></li>
                                                </ul> 
                                            </li> 
                                            <li><a href="<?= $this->basePath() ?>/application/index/products1">Stoles & Scarves</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products1">Handbags</a></li>
                                        </ul>
                                    </li>
                                    <li class="has-children">
                                        <a href="#">BEAUTY</a> 
                                        <ul class="is-hidden">
                                            <li class="go-back"><a href="#">All Fashion Stores</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products1">Perfumes & Deos</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products1">Lipsticks & Nail Polish</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products1">Beauty Gift Hampers</a></li> 
                                            <li><a href="<?= $this->basePath() ?>/application/index/products1">Personal Grooming</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products1">Travel bags</a></li>
                                        </ul>
                                    </li>
                                    <li class="has-children">
                                        <a href="<?= $this->basePath() ?>/application/index/products1">PERSONAL CARE</a> 
                                        <ul class="is-hidden"> 
                                            <li class="go-back"><a href="#">All Fashion Stores</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products1">Face Care</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products1">Nail Care</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products1">Hair Care</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products1">Body Care</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products1">Bath & Spa</a></li>   
                                        </ul>
                                    </li>
                                </ul> <!-- .cd-secondary-dropdown --> 
                            </li> <!-- .has-children -->
                            <li class="has-children">
                                <a href="<?= $this->basePath() ?>/application/index/products2">Kids Fashion & Toys</a> 
                                <ul class="cd-secondary-dropdown is-hidden"> 
                                    <li class="go-back"><a href="#">Menu</a></li>
                                    <li class="see-all"><a href="<?= $this->basePath() ?>/application/index/products2">All Kids Fashions</a></li>
                                    <li class="has-children">
                                        <a href="<?= $this->basePath() ?>/application/index/products2">KIDS CLOTHING</a> 
                                        <ul class="is-hidden"> 
                                            <li class="go-back"><a href="#">All Kids Fashions</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products2">Ethnic wear </a></li> 
                                            <li><a href="<?= $this->basePath() ?>/application/index/products2">inner & Sleepwear </a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products2">Dresses & Frocks </a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products2">Winter wear</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products2">Diaper & Accessories</a></li>
                                        </ul>
                                    </li> 
                                    <li class="has-children"><a href="#">KIDS FASHION</a>
                                        <ul class="is-hidden">  
                                            <li class="go-back"><a href="#">All Kids Fashions</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products2">Footwear</a></li> 
                                            <li><a href="<?= $this->basePath() ?>/application/index/products2">Sunglasses </a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products2">School & Stationery</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products2">Jewellery</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products2">Hair bands & Clips</a></li>
                                        </ul>
                                    </li>
                                    <li class="has-children"><a href="#">Baby Care</a>
                                        <ul class="is-hidden"> 
                                            <li class="go-back"><a href="#">All Kids Fashions</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products2">Lotions, Oil & Powder </a></li> 
                                            <li><a href="<?= $this->basePath() ?>/application/index/products2">Soaps, Shampoo </a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products2">Bath Towels</a></li> 
                                            <li class="has-children">
                                                <a href="#">Feeding</a> 
                                                <ul class="is-hidden">
                                                    <li class="go-back"><a href="#"> </a></li> 
                                                    <li><a href="<?= $this->basePath() ?>/application/index/products2">Baby Food </a></li>
                                                    <li><a href="<?= $this->basePath() ?>/application/index/products2">Bottle Feeding </a></li>
                                                    <li><a href="<?= $this->basePath() ?>/application/index/products2">Breast Feeding</a></li>  
                                                </ul>
                                            </li>  
                                            <li><a href="<?= $this->basePath() ?>/application/index/products2">Toddlers' Rooms</a></li> 	
                                        </ul><!-- .cd-secondary-dropdown --> 
                                    </li> <!-- .has-children -->								
                                    <li class="has-children"><a href="#">TOYS & GAMES </a>
                                        <ul class="is-hidden"> 
                                            <li class="go-back"><a href="#">All Kids Fashions</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products2">Art & Crafts</a></li> 
                                            <li><a href="<?= $this->basePath() ?>/application/index/products2">Educational Toys </a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products2">Baby Toys</a></li> 
                                            <li><a href="<?= $this->basePath() ?>/application/index/products2">Outdoor Play </a></li> 
                                            <li><a href="<?= $this->basePath() ?>/application/index/products2">Musical Instruments</a></li>
                                        </ul>
                                    </li>
                                    <li> 
                                        <ul class="is-hidden">
                                            <li class="go-back"><a href="#">All Kids Fashions</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products2">Toy Tips & Trends</a></li> 
                                            <li><a href="<?= $this->basePath() ?>/application/index/products2">Preschool Toys</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products2">Musical Instruments</a></li> 
                                            <li><a href="<?= $this->basePath() ?>/application/index/products2">Bikes & Ride-Ons</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products2">Video Games</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products2">PC & Digital Gaming</a></li>
                                        </ul>	
                                    </li> 
                                </ul><!-- .cd-secondary-dropdown --> 
                            </li> <!-- .has-children --> 
                            <li class="has-children">
                                <a href="#">Home, Furniture & Patio</a> 
                                <ul class="cd-secondary-dropdown is-hidden">
                                    <li class="go-back"><a href="#">Menu</a></li>
                                    <li class="see-all"><a href="<?= $this->basePath() ?>/application/index/products3">All Products</a></li>
                                    <li class="has-children">
                                        <a href="#">Kitchen Uses</a> 
                                        <ul class="is-hidden">  
                                            <li class="go-back"><a href="#"></a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products3">Dinner Sets </a></li> 
                                            <li><a href="<?= $this->basePath() ?>/application/index/products3">Cookware & Bakeware </a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products3">Containers & Jars </a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products3">Kitchen Tools </a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products3">Food Storage</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products3">Casseroles</a></li>
                                        </ul>
                                    </li> 
                                    <li class="has-children">
                                        <a href="#">Furniture </a> 
                                        <ul class="is-hidden"> 
                                            <li class="go-back"><a href="#"></a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products3">Bedroom </a></li> 
                                            <li><a href="<?= $this->basePath() ?>/application/index/products3">Dining Room </a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products3">Kids' Furniture </a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products3">Living Room</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products3">Office</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products3">Mattresses</a></li>
                                        </ul>
                                    </li> 
                                    <li class="has-children">
                                        <a href="#">Home Decor </a> 
                                        <ul class="is-hidden">
                                            <li class="go-back"><a href="#"></a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products3">Lighting</a></li> 
                                            <li><a href="<?= $this->basePath() ?>/application/index/products3">Painting</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products3">Curtains & Blinds</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products3">Patio Furniture</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products3">Wardrobes & Cabinets</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products3">Mattresses</a></li>
                                        </ul>
                                    </li>  
                                    <li class="has-children">
                                        <a href="#">Gardening & Lawn </a> 
                                        <ul class="is-hidden">
                                            <li class="go-back"><a href="#"> </a></li>  
                                            <li><a href="<?= $this->basePath() ?>/application/index/products3">Gardening </a></li> 
                                            <li><a href="<?= $this->basePath() ?>/application/index/products3">Landscaping </a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products3">Sheds</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products3">Outdoor Storage  </a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products3">Garden & Ideas </a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products3">Patio Tips</a></li>
                                        </ul>
                                    </li> 
                                    <li class="has-children">
                                        <a href="#">Garage Storage</a> 
                                        <ul class="is-hidden"> 
                                            <li class="go-back"><a href="#"></a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products3">Baskets & Bins </a></li> 
                                            <li><a href="<?= $this->basePath() ?>/application/index/products3">Garage Door Openers</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products3">Free Standing Shelves </a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products3">Floor cleaning</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products3">Tool Kits</a></li>
                                        </ul>
                                    </li>  
                                </ul><!-- .cd-secondary-dropdown --> 
                            </li> <!-- .has-children -->  
                            <li class="has-children">
                                <a href="#">Sports, Fitness & Outdoor</a>
                                <ul class="cd-secondary-dropdown is-hidden">
                                    <li class="go-back"><a href="#">Menu</a></li>
                                    <li class="see-all"><a href="<?= $this->basePath() ?>/application/index/products4">All Products</a></li>
                                    <li class="has-children">
                                        <a href="#">Single Sports </a> 
                                        <ul class="is-hidden">
                                            <li class="go-back"><a href="#"></a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products4">Bikes </a></li> 
                                            <li><a href="<?= $this->basePath() ?>/application/index/products4">Fishing  </a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products4">Cycling </a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products4">Musical Instruments</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products4">Archery </a></li>
                                        </ul>
                                    </li> 
                                    <li class="has-children">
                                        <a href="#">Team Sports</a> 
                                        <ul class="is-hidden"> 
                                            <li class="go-back"><a href="#"></a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products4">Cricket </a></li> 
                                            <li><a href="<?= $this->basePath() ?>/application/index/products4">Badminton </a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products4">Swimming Gear </a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products4">Sports Apparel </a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products4">Indoor games</a></li>
                                        </ul>
                                    </li> 
                                    <li class="has-children">
                                        <a href="#">Fitness </a> 
                                        <ul class="is-hidden">
                                            <li class="go-back"><a href="#"></a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products4">Fitness Accessories </a></li> 
                                            <li><a href="<?= $this->basePath() ?>/application/index/products4">Exercise Machines </a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products4">Ellipticals </a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products4">Home Gyms</a></li> 
                                            <li><a href="<?= $this->basePath() ?>/application/index/products4">Exercise Bikes</a></li> 
                                        </ul>
                                    </li>
                                    <li class="has-children">
                                        <a href="#">Camping </a> 
                                        <ul class="is-hidden">
                                            <li class="go-back"><a href="#"></a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products4"> Airbeds</a></li> 
                                            <li><a href="<?= $this->basePath() ?>/application/index/products4">Tents </a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products4">Gazebo's & Shelters</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products4">Coolers </a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products4">Canopies</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products4">Sleeping Bags</a></li>
                                        </ul>
                                    </li> 
                                    <li class="has-children">
                                        <a href="#">Camping Tools</a> 
                                        <ul class="is-hidden">
                                            <li class="go-back"><a href="#"></a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products4">Shooting </a></li> 
                                            <li><a href="<?= $this->basePath() ?>/application/index/products4">Knives & Tools </a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products4">Optics & Binoculars </a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products4">Lights & Lanterns </a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products4">Hunting Clothing </a></li>
                                        </ul>
                                    </li> 
                                    <li class="has-children">
                                        <a href="#">Other</a> 
                                        <ul class="is-hidden">
                                            <li class="go-back"><a href="#"></a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products4">Riding Gears & More </a></li> 
                                            <li><a href="<?= $this->basePath() ?>/application/index/products4">Body Massagers </a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products4">Health Monitors </a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products4">Health Drinks </a></li> 
                                        </ul>
                                    </li> 	
                                </ul><!-- .cd-secondary-dropdown --> 
                            </li> <!-- .has-children -->  
                            <li class="has-children">
                                <a href="#">Grocery store</a>
                                <ul class="cd-secondary-dropdown is-hidden">
                                    <li class="go-back"><a href="#">Menu</a></li>
                                    <li class="see-all"><a href="<?= $this->basePath() ?>/application/index/products5">All Products</a></li>
                                    <li class="has-children">
                                        <a href="#">Veggies & Fruits </a> 
                                        <ul class="is-hidden">
                                            <li class="go-back"><a href="#"></a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products5">Vegetables </a></li> 
                                            <li><a href="<?= $this->basePath() ?>/application/index/products5">Fruits </a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products5">Dry Fruits</a></li> 
                                            <li><a href="<?= $this->basePath() ?>/application/index/products5">Snacks & Cookies </a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products5">Breakfast & Cereal</a></li> 
                                        </ul> 
                                    </li> 
                                    <li class="has-children">
                                        <a href="#">Packet Food</a> 
                                        <ul class="is-hidden">
                                            <li class="go-back"><a href="#"></a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products5">Beverages </a></li> 
                                            <li><a href="<?= $this->basePath() ?>/application/index/products5">Baking </a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products5">Emergency Food </a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products5">Candy & Gum </a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products5">Meals & Pasta </a></li>
                                        </ul>
                                    </li> 
                                    <li class="has-children">
                                        <a href="#">Shop All Pets </a> 
                                        <ul class="is-hidden">
                                            <li class="go-back"><a href="#"></a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products5">Dogs </a></li>  
                                            <li><a href="<?= $this->basePath() ?>/application/index/products5">Fish </a></li>												
                                            <li><a href="<?= $this->basePath() ?>/application/index/products5">Cats</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products5">Birds </a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products5">Pet Food </a></li>
                                        </ul>
                                    </li>
                                    <li class="has-children">
                                        <a href="#">Household Essentials </a> 
                                        <ul class="is-hidden"> 
                                            <li class="go-back"><a href="#"></a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Laundry Room </a></li> 
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Paper & Plastic</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Pest Control </a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Batteries </a></li> 
                                        </ul>
                                    </li> 
                                    <li class="has-children">
                                        <a href="#">Food Shops </a> 
                                        <ul class="is-hidden">
                                            <li class="go-back"><a href="#"></a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Fresh Food</a></li> 
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Food Gifts </a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Frozen Food </a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Organic </a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/productshtml">Gluten Free </a></li>
                                        </ul>
                                    </li> 
                                    <li class="has-children">
                                        <a href="#">Tips </a> 
                                        <ul class="is-hidden">
                                            <li class="go-back"><a href="#"></a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Pets Growth</a></li> 
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Recipes </a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Snacks</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Nutrition</a></li> 
                                        </ul>
                                    </li> 
                                </ul><!-- .cd-secondary-dropdown --> 
                            </li> <!-- .has-children -->  
                            <li class="has-children">
                                <a href="#">Photo, Gifts & Office Supplies</a>
                                <ul class="cd-secondary-dropdown is-hidden">
                                    <li class="go-back"><a href="#">Menu</a></li>
                                    <li class="see-all"><a href="<?= $this->basePath() ?>/application/index/products6">All Products</a></li>
                                    <li class="has-children">
                                        <a href="#">Trending Now </a> 
                                        <ul class="is-hidden">
                                            <li class="go-back"><a href="#"></a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Best Priced</a></li> 
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Chocolates </a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Gift Cards </a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Fashion & Accessories </a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Decorative Plants </a></li>
                                        </ul>
                                    </li> 
                                    <li class="has-children">
                                        <a href="#">Photos </a> 
                                        <ul class="is-hidden">
                                            <li class="go-back"><a href="#"></a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Shelf animation </a></li> 
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">3D-rendered </a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">gift builder </a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Frames</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Wall Decor</a></li>
                                        </ul>
                                    </li> 
                                    <li class="has-children">
                                        <a href="#">Gifts </a> 
                                        <ul class="is-hidden">	
                                            <li class="go-back"><a href="#"></a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Personalized Gifts </a></li> 
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Flowers </a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Cards & Toys</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Show pieces </a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Photo Books</a></li>
                                        </ul>
                                    </li>
                                    <li class="has-children">
                                        <a href="#">Favourite Brands </a> 
                                        <ul class="is-hidden">
                                            <li class="go-back"><a href="#"></a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Archies </a></li> 
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Jewel Fuel </a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Ferns N Petals </a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Happily Unmarried</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Chumbak</a></li>
                                        </ul>
                                    </li> 
                                    <li class="has-children">
                                        <a href="#">Office</a> 
                                        <ul class="is-hidden"> 
                                            <li class="go-back"><a href="#"></a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Calendars</a></li> 
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Mousepads</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Phone Cases</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Tablet & Laptop Cases</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Mounted Photos</a></li>
                                        </ul>
                                    </li> 
                                    <li class="has-children">
                                        <a href="#">Combos </a> 
                                        <ul class="is-hidden">
                                            <li class="go-back"><a href="#"></a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Chocolates </a></li> 
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Dry Fruits</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Sweets</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Snacks</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Cakes</a></li>
                                        </ul>
                                    </li> 
                                </ul><!-- .cd-secondary-dropdown --> 
                            </li> 
                            <li class="has-children">
                                <a href="#">Health, Beauty & Pharmacy</a>
                                <ul class="cd-secondary-dropdown is-hidden">
                                    <li class="go-back"><a href="#">Menu</a></li>
                                    <li class="see-all"><a href="<?= $this->basePath() ?>/application/index/products7">All Products</a></li>
                                    <li class="has-children">
                                        <a href="#">Health</a> 
                                        <ul class="is-hidden">
                                            <li class="go-back"><a href="#"></a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Home Health Care </a></li> 
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Sports Nutrition </a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Vision </a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Vitamins </a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Diet & Nutrition </a></li>
                                        </ul>
                                    </li> 
                                    <li class="has-children">
                                        <a href="#">Health Tips</a> 
                                        <ul class="is-hidden">
                                            <li class="go-back"><a href="#"></a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Diet</a></li> 
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Exercise Tips  </a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Vitamin Balance</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Health Insurance</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Funeral</a></li>
                                        </ul>
                                    </li> 
                                    <li class="has-children">
                                        <a href="#">Beauty </a> 
                                        <ul class="is-hidden">
                                            <li class="go-back"><a href="#"></a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Massage & Spa </a></li> 
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Face Wash</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Facial Cleanser</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Makeup </a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Beauty Tips</a></li>
                                        </ul>
                                    </li>
                                    <li class="has-children">
                                        <a href="#">Pharmacy </a> 
                                        <ul class="is-hidden">
                                            <li class="go-back"><a href="#"></a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Home Delivery </a></li> 
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">History & Reports </a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Transfer Prescriptions </a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Health CheckUp</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Mobile App</a></li>
                                        </ul>
                                    </li> 
                                    <li class="has-children">
                                        <a href="#">Pharmacy Center </a> 
                                        <ul class="is-hidden">
                                            <li class="go-back"><a href="#"></a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Diabetes Shop </a></li> 
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Medicine Cabinet </a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Vitamin Selector</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products">Pharmacy Help</a></li> 
                                        </ul>
                                    </li>  
                                </ul><!-- .cd-secondary-dropdown --> 
                            </li>
                            <li class="has-children">
                                <a href="#">Automotive</a>
                                <ul class="cd-secondary-dropdown is-hidden">
                                    <li class="go-back"><a href="#">Menu</a></li>
                                    <li class="see-all"><a href="<?= $this->basePath() ?>/application/index/products8">All Products</a></li>
                                    <li class="has-children">
                                        <a href="#">All Motors </a> 
                                        <ul class="is-hidden">
                                            <li class="go-back"><a href="#"></a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products8">Bikes </a></li> 
                                            <li><a href="<?= $this->basePath() ?>/application/index/products8">Yachts </a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products8">Scooters </a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products8">Autos</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products8">Bus</a></li>
                                        </ul>
                                    </li> 
                                    <li class="has-children">
                                        <a href="#">Accessories </a> 
                                        <ul class="is-hidden">
                                            <li class="go-back"><a href="#"></a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products8">Vehicle Electronics</a></li> 
                                            <li><a href="<?= $this->basePath() ?>/application/index/products8">Stereos & Monitors</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products8">Bluetooth Devices</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products8">GPS Navigation</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products8">Speakers & Tweeters</a></li>
                                        </ul>
                                    </li> 
                                    <li class="has-children">
                                        <a href="#">Safety & Security </a> 
                                        <ul class="is-hidden">
                                            <li class="go-back"><a href="#"></a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products8">Anti-Theft Devices </a></li> 
                                            <li><a href="<?= $this->basePath() ?>/application/index/products8">Helmets</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products8">Sensors</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products8">Auto Repair Tools </a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products8">Antifreeze & Coolants </a></li>
                                        </ul>
                                    </li>
                                    <li class="has-children">
                                        <a href="#">Car Interiors</a> 
                                        <ul class="is-hidden">
                                            <li class="go-back"><a href="#"></a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products8">Stereos </a></li> 
                                            <li><a href="<?= $this->basePath() ?>/application/index/products8">Floor Mats </a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products8">Seat Covers</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products8">Chargers </a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products8">Audio Finder </a></li>
                                        </ul>
                                    </li>  
                                    <li class="has-children">
                                        <a href="#">Exterior Accessories </a> 
                                        <ul class="is-hidden"> 
                                            <li class="go-back"><a href="#"></a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products8">Wheel covers </a></li> 
                                            <li><a href="<?= $this->basePath() ?>/application/index/products8">Car Lighting </a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products8">Polish & Waxes</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products8">Cargo Management</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products8">Car Decoration </a></li>
                                        </ul>
                                    </li> 
                                    <li class="has-children">
                                        <a href="#">Car Care</a> 
                                        <ul class="is-hidden">
                                            <li class="go-back"><a href="#"></a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products8">Auto Tips & Advice </a></li> 
                                            <li><a href="<?= $this->basePath() ?>/application/index/products8">Car Washes & Cleaners </a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products8">Car Wax & Polish</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products8">Cleaning Tools</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products8">Detailing Kits </a></li>
                                        </ul>
                                    </li> 
                                </ul><!-- .cd-secondary-dropdown --> 
                            </li>
                            <li class="has-children">
                                <a href="#">Books, Music & Movies</a>
                                <ul class="cd-secondary-dropdown is-hidden">
                                    <li class="go-back"><a href="#">Menu</a></li>
                                    <li class="see-all"><a href="<?= $this->basePath() ?>/application/index/products9">All Products</a></li>
                                    <li class="has-children">
                                        <a href="#">Books</a> 
                                        <ul class="is-hidden">
                                            <li class="go-back"><a href="#"></a></li>
                                            <li class="has-children"><a href="#">Exam books </a>
                                                <ul class="is-hidden">
                                                    <li class="go-back"><a href="#"> </a></li>
                                                    <li><a href="<?= $this->basePath() ?>/application/index/products9">CAT/MAT/XAT</a></li>
                                                    <li><a href="<?= $this->basePath() ?>/application/index/products9">Civil Services</a></li>
                                                    <li><a href="<?= $this->basePath() ?>/application/index/products9">AFCAT</a></li>
                                                    <li><a href="<?= $this->basePath() ?>/application/index/products9">New Releases</a></li>
                                                </ul>												
                                            </li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products9">Academic Text </a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products9">Romance Books </a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products9">Journals </a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products9">Children's & Teen Books </a></li>
                                        </ul>
                                    </li> 
                                    <li class="has-children">
                                        <a href="#">Music</a> 
                                        <ul class="is-hidden">
                                            <li class="go-back"><a href="#"></a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products9">New Releases </a></li> 
                                            <li><a href="<?= $this->basePath() ?>/application/index/products9">Country Music </a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products9">Musical Instruments </a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products9">Collections</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products9">Boxed Sets </a></li>
                                        </ul>
                                    </li> 
                                    <li class="has-children">
                                        <a href="#">Music Combo</a> 
                                        <ul class="is-hidden">
                                            <li class="go-back"><a href="#"></a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products9">Pop </a></li> 
                                            <li><a href="<?= $this->basePath() ?>/application/index/products9">Preorders </a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products9">Album Songs</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products9">Top 50 CDs </a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products9">Music DVDs </a></li>
                                        </ul>
                                    </li>
                                    <li class="has-children">
                                        <a href="#">Movies</a> 
                                        <ul class="is-hidden"> 
                                            <li class="go-back"><a href="#"></a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products9">New Releases </a></li> 
                                            <li><a href="<?= $this->basePath() ?>/application/index/products9">Children & Family </a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products9">Action</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products9">Classic Movies </a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products9">Bollywood Movies </a></li>
                                        </ul>
                                    </li> 
                                    <li class="has-children">
                                        <a href="#">Movies Combo</a> 
                                        <ul class="is-hidden">
                                            <li class="go-back"><a href="#"></a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products9">Hollywood Movies </a></li> 
                                            <li><a href="<?= $this->basePath() ?>/application/index/products9">Digital Movies </a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products9">Boxed Sets</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products9">Animated</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products9">Adventure</a></li>
                                        </ul>
                                    </li> 
                                    <li class="has-children">
                                        <a href="#">TV Shows</a> 
                                        <ul class="is-hidden">
                                            <li class="go-back"><a href="#"></a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products9">Serials</a></li> 
                                            <li><a href="<?= $this->basePath() ?>/application/index/products9">Best Programs</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products9">Celebrations</a></li>
                                            <li><a href="<?= $this->basePath() ?>/application/index/products9">Top Shows</a></li> 
                                        </ul>
                                    </li> 
                                </ul><!-- .cd-secondary-dropdown --> 
                            </li>  
                            <li><a href="sitemap">Full Site Directory </a></li>  
                        </ul> <!-- .cd-dropdown-content -->
                    </nav> <!-- .cd-dropdown -->
                </div> <!-- .cd-dropdown-wrapper -->	 
            </div>
        </div>
    </div>
</div>
<script>
    var serverAppUrl = '<?php echo $GLOBALS['SITE_APP_URL']; ?>';
</script>