<head>
    <title>Afro Basket an E-commerce Online Shopping Category</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Afro Basket Responsive web template" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false);
        function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!-- Custom Theme files -->
    <link href="<?php echo $this->basePath() ?>/public/css/bootstrap.min.css" rel="stylesheet" type="text/css" media="all" />
    <link href="<?php echo $this->basePath() ?>/public/css/bootstrap.css" rel="stylesheet" type="text/css" media="all" />
    <link href="<?php echo $this->basePath() ?>/public/css/style.css" rel="stylesheet" type="text/css" media="all" /> 
    <link href="<?php echo $this->basePath() ?>/public/css/menu.css" rel="stylesheet" type="text/css" media="all" /> <!-- menu style --> 
    <link href="<?php echo $this->basePath() ?>/public/css/ken-burns.css" rel="stylesheet" type="text/css" media="all" /> <!-- banner slider --> 
    <link href="<?php echo $this->basePath() ?>/public/css/animate.min.css" rel="stylesheet" type="text/css" media="all" /> 
    <link href="<?php echo $this->basePath() ?>/public/css/owl.carousel.css" rel="stylesheet" type="text/css" media="all"> <!-- carousel slider -->  
    <link href="<?php echo $this->basePath() ?>/public/css/slider.css" rel="stylesheet" type="text/css" media="all">    
    <link href="<?php echo $this->basePath() ?>/public/css/location.css" rel="stylesheet" type="text/css" media="all">   
     <link href="<?php echo $this->basePath() ?>/public/css/jquery-ui.css" rel="stylesheet" type="text/css" media="all">   
    <!-- //Custom Theme files -->
    <!-- font-awesome icons -->
    <link href="<?php echo $this->basePath() ?>/public/css/font-awesome.css" rel="stylesheet"> 
    <!-- //font-awesome icons -->
    <!-- js -->
    <!-- //js --> 
    <!-- web-fonts -->
    <!-- web-fonts --> 
    <style> 
        .owl-nav{position: absolute; top: 0; left: 0;width: 100%; margin: 0;}
        .owl-carousel .owl-nav .owl-prev{position: absolute;left: -5px; top: 0; height: 300px; width: 30px; margin: 0; }
        .owl-carousel .owl-nav .owl-next{position: absolute;right: 0px; top: 0; height: 300px; width: 30px; margin: 0;}
        .owl-carousel .owl-item .merchant img{width: 80%;}
        .merchant_name{font-size: 16px;}
    </style>
</head>
<div ng-app="app">
<div class="header">
    <div class="w3ls-header"><!--header-one--> 
        <div class="w3ls-header-left">
            <p>SALE UP TO 70% OFF. USE CODE "SALE70%" . <a href="<?= $this->basePath() ?>/application/index/products">SHOP NOW</a></p>
        </div>                
        <div class="clearfix"> </div> 
    </div>
    <div class="header-two"> 
        <div class="container no-lpad no-rpad">
            <div class="header-logo">
                <a href="<?=$this->basePath()?>">
                <img src="<?php echo $this->basePath() ?>/public/images/logo-big.png" alt="logo"/> 
                </a>
            </div>	
            <div class="header-city">
                <select class="form-control select2" style="width: 100%;">
                    <?php
                        foreach ($GLOBALS['city_list'] as $key => $value) {
                            echo'<option value="'.$value['id'].'">'.$value['city_name'].'</option>';
                        }
                    ?>
                    </select>
                <!--<a class="cd-dropdown-trigger" href="#" id="city-link"  style="color:#000000;">Select Your City</a>-->
            </div>
            <div class="header-search">
                <form action="<?=$this->basePath()?>/application/index/product" method="post">
                    <input type="search" name="search" placeholder="Search for a Product..." required="">
                    <button type="submit" class="btn btn-default" aria-label="Left Align">
                        <i class="fa fa-search" aria-hidden="true"> </i>                            
                    </button>
                </form>
            </div>
            <div class="header-cart"> 
                <div class="dropdown my-account">
                    <?php
                        if(!empty($GLOBALS['user'])){
                    ?>
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-user" aria-hidden="true"></i> My Account <b class="caret"></b></a>
                    <ul class="dropdown-menu multi-column columns-3 pull-right">
                        <div class="row">
                            <div class="multi-gd-img">
                                <ul class="multi-column-dropdown">
                                    <li><a href="<?=$this->basePath()?>/application/index/editprofile">Account Setting</a></li>
                                    <li><a href="<?=$this->basePath()?>/application/index/currentorder">My Order</a></li>
                                    <li><a href="<?=$this->basePath()?>/application/index/pastorder">Past Order </a></li>
                                    <li><a href="<?=$this->basePath()?>/application/index/changepassword">Change Password</a></li> 
                                    <li><a href="<?=$this->basePath()?>/application/index/logout">Log-out</a></li> 
                                </ul>
                            </div>
                        </div>
                    </ul>
                    <?php }else{ ?>
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-user" aria-hidden="true"></i> Your Account  <b class="caret"></b></a>
                    <ul class="dropdown-menu multi-column columns-3 pull-right">
                        <div class="row">
                            <div class="multi-gd-img">
                                <ul class="multi-column-dropdown">
                                    <li><a href="<?=$this->basePath()?>/application/index/signup">Signup</a></li>
                                    <li><a href="<?=$this->basePath()?>/application/index/login">Login</a></li>
                                </ul>
                            </div>
                        </div>
                    </ul>
                    <?php }?>
                </div>
                <div class="cart" ng-controller="cartcontroller"> 
                    <a ng-click="cartList()" class="w3view-cart" id="w3view-cart"><i class="fa fa-cart-arrow-down" aria-hidden="true"></i></a>
                     My Cart
                    <ul class="dropdown-menu  multi-column columns-5 pull-right w3view-cart-menu">
                        <div class="row">
                            <a href="#" class="w3view-cart-close">X</a>
                            <div class="cart-gd-img">
                                <ul class="cart-column-dropdown">
                                    <li ng-repeat="cartItem in cartResponse.data">
                                        <img src="{{cartResponse.imageRootPath}}/{{cartResponse.productDetails.productImageData[cartResponse.productDetails.data[cartItem.merchant_inventry_id].product_id][0].type}}/{{cartResponse.productDetails.data[cartItem.merchant_inventry_id].product_id}}/{{cartResponse.productDetails.productImageData[cartResponse.productDetails.data[cartItem.merchant_inventry_id].product_id][0].image_name}}"/>
                                        <span class="title">{{cartItem.item_name}}<br>
                                            <span class="item-quant">Item:  {{cartItem.number_of_item}}</span>
                                            <i class="fa fa-plus green-text" ng-click="addToCart(cartItem.merchant_inventry_id, cartItem.item_name, 'add', 1)"></i> <i class="fa fa-minus red-text" ng-click="addToCart(cartItem.merchant_inventry_id, cartItem.item_name, 'delete', 1)"></i>
                                        </span> <span class="price">GHC {{cartResponse.productDetails.data[cartItem.merchant_inventry_id].price}}</span>
                                    </li>
                                    <li ng-if="cartResponse.data">
                                        <a class="button conti" href="<?= $this->basePath() ?>">Continue Shopping</a> 
					<a class="button proceed" href="<?= $this->basePath() ?>/application/index/checkout" class="cart" id="cart" >Proceed To Checkout</a>
				  </li>                                    
                                </ul>
                            </div>	
                        </div>
                    </ul>
                </div>
                <div class="clearfix"> </div> 
            </div> 
            <div class="clearfix"> </div>
        </div>		
    </div><!-- //header-two -->
    <!-- navigation -->

    <!-- //navigation -->
</div>
<script>
    var serverAppUrl = '<?php echo $GLOBALS['SITE_APP_URL']; ?>';
</script>