<?php 
echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <?php 
            echo $this->headScript()
                ->prependFile($this->basePath() . '/public/js/common.js')
                ->prependFile($this->basePath() . '/public/js/ui-bootstrap-tpls-0.12.1.min.js')
                ->prependFile($this->basePath().'/public/js/angular.min.js')
                ->prependFile($this->basePath() . '/public/js/bootstrap.min.js')
                ->prependFile($this->basePath() . '/public/js/jquery-ui.js')
                ->prependFile($this->basePath() . '/public/js/jquery.min.js');
        ?>        
    </head>
   
    <?php
        echo $this->partial('layout/header');
    ?>
    <?php
       if(in_array($GLOBALS['action'], $GLOBALS['LEFT_MENU_ALLOW'])){
           echo $this->partial('application/partial/leftMenu.phtml');
       }
       
    ?>    
        
        
            <?php 
            echo $this->content; ?>
            <?php
    echo $this->partial('layout/footer');
    ?>        
               
        <?php echo $this->inlineScript() ?>
 
</html>
