<?php
        echo $this->partial('layout/header');
        if(in_array($GLOBALS['action'], $GLOBALS['LEFT_MENU_ALLOW'])){
            ?>
        <div class="page-heading">
            <div class="breadcrumbs">
                <div class="container">
                    <div class="row">
                        <div class="col-xs-12">
                            <ul>
                                <li class="home"> <a href="index.html" title="Go to Home Page">Home</a> <span>כ </span> </li>
                                <li class="category1599"> <a href="grid.html" title="">Salad</a> <span>כ </span> </li>
                                <li class="category1600"> <a href="grid.html" title="">Bread Salad</a> <span>כ </span> </li>
                                <li class="category1601"> <strong>Dakos</strong> </li>
                            </ul>
                        </div>
                        <!--col-xs-12--> 
                    </div>
                    <!--row--> 
                </div>
                <!--container--> 
            </div>
            <div class="page-title">
                <h2>Cappon Magro</h2>
            </div>
        </div>    
        <section class="main-container col2-left-layout bounceInUp animated">
            <div class="container"> 
                <div class="row">
    <?php
        }
       echo $this->content; 
       if(in_array($GLOBALS['action'], $GLOBALS['LEFT_MENU_ALLOW'])){
           echo $this->partial('application/partial/leftMenu.phtml');
        ?>
                </div>
            </div>
        </section>
        <?php
       }
       
    ?>    
      
            <?php
            
            echo $this->partial('layout/footer');
    ?>        
               
        <?php //echo $this->inlineScript() ?>
 
</html>
